"""Tests for src/reference_stub_enricher — LLM-based vault stub enrichment."""

from __future__ import annotations

import os
from dataclasses import dataclass
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from src.reference_stub_enricher import (
    SUMMARIZE_SYSTEM_PROMPT,
    ReferenceStubEnricher,
    StaleScanResult,
    StaleStubInfo,
    extract_last_synced_from_frontmatter,
    extract_source_hash_from_frontmatter,
    extract_source_path_from_frontmatter,
    parse_enrichment_response,
    scan_stale_stubs,
    stub_is_enriched,
    update_stub_content,
)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@dataclass
class FakeChatResponse:
    """Minimal ChatResponse stand-in for testing."""

    content: list

    @property
    def text_parts(self) -> list[str]:
        return [block.text for block in self.content if hasattr(block, "text")]


@dataclass
class FakeTextBlock:
    text: str


@pytest.fixture
def fake_bus():
    bus = MagicMock()
    bus.emit = AsyncMock()
    bus.subscribe = MagicMock(return_value=MagicMock())
    return bus


@pytest.fixture
def fake_config():
    """Minimal MemoryConfig-like object with stub_enrichment fields."""

    @dataclass
    class FakeMemoryConfig:
        stub_enrichment_enabled: bool = True
        stub_enrichment_provider: str = ""
        stub_enrichment_model: str = ""
        stub_enrichment_max_source_chars: int = 20_000
        revision_provider: str = ""
        revision_model: str = ""

    return FakeMemoryConfig()


@pytest.fixture
def fake_provider():
    """Mock ChatProvider that returns a well-structured LLM response."""
    provider = AsyncMock()
    provider.create_message = AsyncMock(
        return_value=FakeChatResponse(
            content=[
                FakeTextBlock(
                    text=(
                        "## Summary\n"
                        "This document defines the main orchestration loop "
                        "including task assignment and agent lifecycle.\n\n"
                        "## Key Decisions\n"
                        "- Tick-based loop at ~5s interval\n"
                        "- Single agent per task\n"
                        "- Tasks assigned by priority then age\n\n"
                        "## Key Interfaces\n"
                        "- `Orchestrator.tick()` -- main loop entry\n"
                        "- `Orchestrator.assign_task()` -- agent selection\n"
                        "- EventBus integration for state changes"
                    )
                )
            ]
        )
    )
    return provider


@pytest.fixture
def vault_dir(tmp_path):
    """Create a vault/projects directory structure."""
    vault_projects = tmp_path / "vault" / "projects"
    vault_projects.mkdir(parents=True)
    return str(vault_projects)


@pytest.fixture
def enricher(fake_bus, vault_dir, fake_config, fake_provider):
    """Create a ReferenceStubEnricher with a mock provider."""
    return ReferenceStubEnricher(
        bus=fake_bus,
        vault_projects_dir=vault_dir,
        config=fake_config,
        provider=fake_provider,
        enabled=True,
    )


def _create_stub_file(vault_dir: str, project_id: str, stub_name: str) -> str:
    """Create a stub file with placeholder sections.

    Returns the path to the created stub file.
    """
    refs_dir = os.path.join(vault_dir, project_id, "references")
    os.makedirs(refs_dir, exist_ok=True)
    stub_path = os.path.join(refs_dir, stub_name)

    content = f"""\
---
tags: [spec, reference, auto-generated]
source: /workspace/specs/orchestrator.md
source_hash: abc123def456
last_synced: 2026-04-07
---

# Spec: Orchestrator

Full spec at `specs/orchestrator.md` in the {project_id} workspace.

## Excerpt

First few lines of the spec...

## Summary

*Summary pending -- will be generated by LLM enrichment.*

## Key Decisions

*Pending LLM extraction.*

## Key Interfaces

*Pending LLM extraction.*
"""
    with open(stub_path, "w", encoding="utf-8") as f:
        f.write(content)
    return stub_path


def _create_source_file(tmp_path, content: str = "") -> str:
    """Create a source spec file and return its path."""
    source = tmp_path / "workspace" / "specs" / "orchestrator.md"
    source.parent.mkdir(parents=True, exist_ok=True)
    if not content:
        content = """\
# Orchestrator Spec

## Overview
The orchestrator manages the main loop for task assignment.

## Design Decisions
- Tick-based loop at ~5s interval
- Single agent per task, no sharing
- Tasks assigned by priority then age

## Interfaces
- `Orchestrator.tick()` -- main loop entry
- `Orchestrator.assign_task()` -- agent selection
"""
    source.write_text(content, encoding="utf-8")
    return str(source)


def _create_enriched_stub_file(
    vault_dir: str,
    project_id: str,
    stub_name: str,
    source_hash: str = "abc123def456",
) -> str:
    """Create a stub file with enriched (non-placeholder) LLM sections.

    Returns the path to the created stub file.
    """
    refs_dir = os.path.join(vault_dir, project_id, "references")
    os.makedirs(refs_dir, exist_ok=True)
    stub_path = os.path.join(refs_dir, stub_name)

    content = f"""\
---
tags: [spec, reference, auto-generated]
source: /workspace/specs/orchestrator.md
source_hash: {source_hash}
last_synced: 2026-04-07
---

# Spec: Orchestrator

Full spec at `specs/orchestrator.md` in the {project_id} workspace.

## Excerpt

First few lines of the spec...

## Summary

This document defines the main orchestration loop including task assignment and agent lifecycle.

## Key Decisions

- Tick-based loop at ~5s interval
- Single agent per task
- Tasks assigned by priority then age

## Key Interfaces

- `Orchestrator.tick()` -- main loop entry
- `Orchestrator.assign_task()` -- agent selection
- EventBus integration for state changes
"""
    with open(stub_path, "w", encoding="utf-8") as f:
        f.write(content)
    return stub_path


# ---------------------------------------------------------------------------
# parse_enrichment_response tests
# ---------------------------------------------------------------------------


class TestParseEnrichmentResponse:
    """Tests for the parse_enrichment_response() function."""

    def test_parses_well_formed_response(self):
        response = (
            "## Summary\n"
            "This is the summary.\n\n"
            "## Key Decisions\n"
            "- Decision one\n"
            "- Decision two\n\n"
            "## Key Interfaces\n"
            "- `foo()` -- does things\n"
            "- `bar()` -- does other things"
        )
        result = parse_enrichment_response(response)
        assert "summary" in result["summary"].lower() or "This is the summary" in result["summary"]
        assert "Decision one" in result["key_decisions"]
        assert "`foo()`" in result["key_interfaces"]

    def test_empty_response_returns_empty_sections(self):
        result = parse_enrichment_response("")
        assert result["summary"] == ""
        assert result["key_decisions"] == ""
        assert result["key_interfaces"] == ""

    def test_partial_response_fills_available_sections(self):
        response = "## Summary\nJust a summary, no other sections."
        result = parse_enrichment_response(response)
        assert "Just a summary" in result["summary"]
        assert result["key_decisions"] == ""
        assert result["key_interfaces"] == ""

    def test_case_insensitive_headers(self):
        response = (
            "## summary\n"
            "Lower case summary.\n\n"
            "## KEY DECISIONS\n"
            "- Upper case decision\n\n"
            "## Key Interfaces\n"
            "- Mixed case interface"
        )
        result = parse_enrichment_response(response)
        assert "Lower case summary" in result["summary"]
        assert "Upper case decision" in result["key_decisions"]
        assert "Mixed case interface" in result["key_interfaces"]

    def test_extra_headers_ignored(self):
        response = (
            "## Summary\n"
            "The summary.\n\n"
            "## Additional Notes\n"
            "These are extra notes.\n\n"
            "## Key Decisions\n"
            "- A decision\n\n"
            "## Key Interfaces\n"
            "- An interface"
        )
        result = parse_enrichment_response(response)
        assert "The summary" in result["summary"]
        assert "A decision" in result["key_decisions"]
        assert "An interface" in result["key_interfaces"]

    def test_multiline_content_preserved(self):
        response = (
            "## Summary\n"
            "Line one of summary.\n"
            "Line two of summary.\n"
            "Line three.\n\n"
            "## Key Decisions\n"
            "- Decision A\n"
            "- Decision B\n"
            "- Decision C\n\n"
            "## Key Interfaces\n"
            "- Interface X"
        )
        result = parse_enrichment_response(response)
        assert "Line one" in result["summary"]
        assert "Line three" in result["summary"]
        assert "Decision A" in result["key_decisions"]
        assert "Decision C" in result["key_decisions"]


# ---------------------------------------------------------------------------
# update_stub_content tests
# ---------------------------------------------------------------------------


class TestUpdateStubContent:
    """Tests for the update_stub_content() function."""

    def test_replaces_placeholder_summary(self):
        existing = (
            "# Spec: Foo\n\n"
            "## Excerpt\n\nSome excerpt.\n\n"
            "## Summary\n\n"
            "*Summary pending -- will be generated by LLM enrichment.*\n\n"
            "## Key Decisions\n\n"
            "*Pending LLM extraction.*\n\n"
            "## Key Interfaces\n\n"
            "*Pending LLM extraction.*\n"
        )
        sections = {
            "summary": "This is the real summary.",
            "key_decisions": "- Real decision",
            "key_interfaces": "- `real_fn()` -- does stuff",
        }
        result = update_stub_content(existing, sections)
        assert "This is the real summary." in result
        assert "- Real decision" in result
        assert "`real_fn()`" in result
        assert "*Summary pending" not in result
        assert "*Pending LLM extraction.*" not in result

    def test_preserves_frontmatter(self):
        existing = (
            "---\ntags: [spec]\nsource: /foo\n---\n\n"
            "# Spec: Bar\n\n"
            "## Excerpt\n\nExcerpt text.\n\n"
            "## Summary\n\n*Placeholder*\n\n"
            "## Key Decisions\n\n*Placeholder*\n\n"
            "## Key Interfaces\n\n*Placeholder*\n"
        )
        sections = {"summary": "New summary.", "key_decisions": "", "key_interfaces": ""}
        result = update_stub_content(existing, sections)
        assert "---\ntags: [spec]\nsource: /foo\n---" in result
        assert "New summary." in result
        # Empty sections should NOT replace existing content
        assert "*Placeholder*" in result

    def test_empty_sections_preserve_existing(self):
        existing = (
            "## Summary\n\nExisting summary.\n\n"
            "## Key Decisions\n\n- Existing decision\n\n"
            "## Key Interfaces\n\n- Existing interface\n"
        )
        sections = {"summary": "", "key_decisions": "", "key_interfaces": ""}
        result = update_stub_content(existing, sections)
        assert result == existing

    def test_preserves_excerpt_section(self):
        existing = (
            "## Excerpt\n\nFirst lines of the file...\n\n"
            "## Summary\n\n*Placeholder*\n\n"
            "## Key Decisions\n\n*Placeholder*\n\n"
            "## Key Interfaces\n\n*Placeholder*\n"
        )
        sections = {
            "summary": "New summary.",
            "key_decisions": "- New decision",
            "key_interfaces": "- New interface",
        }
        result = update_stub_content(existing, sections)
        assert "First lines of the file..." in result
        assert "New summary." in result


# ---------------------------------------------------------------------------
# ReferenceStubEnricher tests
# ---------------------------------------------------------------------------


class TestReferenceStubEnricherSubscribe:
    """Tests for subscription lifecycle."""

    def test_subscribe_calls_bus_subscribe(self, enricher, fake_bus):
        enricher.subscribe()
        fake_bus.subscribe.assert_called_once_with(
            "workspace.spec.changed",
            enricher._on_spec_changed,
        )

    def test_double_subscribe_is_idempotent(self, enricher, fake_bus):
        enricher.subscribe()
        enricher.subscribe()
        fake_bus.subscribe.assert_called_once()

    def test_unsubscribe_calls_unsubscribe_handle(self, enricher, fake_bus):
        enricher.subscribe()
        unsub = fake_bus.subscribe.return_value
        enricher.unsubscribe()
        unsub.assert_called_once()


class TestReferenceStubEnricherProperties:
    """Tests for enricher properties."""

    def test_enabled_default_true(self, enricher):
        assert enricher.enabled is True

    def test_enabled_setter(self, enricher):
        enricher.enabled = False
        assert enricher.enabled is False

    def test_initial_counters_zero(self, enricher):
        assert enricher.total_enriched == 0
        assert enricher.total_failed == 0


class TestReferenceStubEnricherEnrich:
    """Tests for the enrich_stub() method."""

    @pytest.mark.asyncio
    async def test_successful_enrichment(self, enricher, vault_dir, tmp_path):
        project_id = "test-project"
        stub_name = "spec-orchestrator.md"

        # Create source and stub files
        source_path = _create_source_file(tmp_path)
        _create_stub_file(vault_dir, project_id, stub_name)

        result = await enricher.enrich_stub(
            project_id=project_id,
            abs_path=source_path,
            stub_name=stub_name,
        )

        assert result.success is True
        assert result.project_id == project_id
        assert result.stub_name == stub_name
        assert result.summary != ""
        assert result.error == ""
        assert enricher.total_enriched == 1
        assert enricher.total_failed == 0

    @pytest.mark.asyncio
    async def test_enrichment_updates_stub_file(self, enricher, vault_dir, tmp_path):
        project_id = "test-project"
        stub_name = "spec-orchestrator.md"

        source_path = _create_source_file(tmp_path)
        stub_path = _create_stub_file(vault_dir, project_id, stub_name)

        await enricher.enrich_stub(
            project_id=project_id,
            abs_path=source_path,
            stub_name=stub_name,
        )

        # Verify stub file was updated
        with open(stub_path, encoding="utf-8") as f:
            content = f.read()

        assert "*Summary pending" not in content
        assert "orchestration loop" in content.lower() or "task assignment" in content.lower()
        assert "Tick-based loop" in content or "priority" in content.lower()

    @pytest.mark.asyncio
    async def test_missing_source_file_fails(self, enricher, vault_dir):
        project_id = "test-project"
        stub_name = "spec-missing.md"
        _create_stub_file(vault_dir, project_id, stub_name)

        result = await enricher.enrich_stub(
            project_id=project_id,
            abs_path="/nonexistent/file.md",
            stub_name=stub_name,
        )

        assert result.success is False
        assert "Could not read" in result.error
        assert enricher.total_failed == 1

    @pytest.mark.asyncio
    async def test_missing_stub_file_fails(self, enricher, tmp_path):
        project_id = "test-project"
        stub_name = "spec-no-stub.md"
        source_path = _create_source_file(tmp_path)

        result = await enricher.enrich_stub(
            project_id=project_id,
            abs_path=source_path,
            stub_name=stub_name,
        )

        assert result.success is False
        assert "Stub file not found" in result.error

    @pytest.mark.asyncio
    async def test_no_provider_fails(self, fake_bus, vault_dir, fake_config, tmp_path):
        enricher = ReferenceStubEnricher(
            bus=fake_bus,
            vault_projects_dir=vault_dir,
            config=fake_config,
            provider=None,  # No provider
            enabled=True,
        )
        # Patch _get_provider to return None (simulates missing credentials)
        enricher._get_provider = MagicMock(return_value=None)

        project_id = "test-project"
        stub_name = "spec-test.md"
        source_path = _create_source_file(tmp_path)
        _create_stub_file(vault_dir, project_id, stub_name)

        result = await enricher.enrich_stub(
            project_id=project_id,
            abs_path=source_path,
            stub_name=stub_name,
        )

        assert result.success is False
        assert "No LLM provider" in result.error

    @pytest.mark.asyncio
    async def test_llm_exception_fails_gracefully(self, fake_bus, vault_dir, fake_config, tmp_path):
        provider = AsyncMock()
        provider.create_message = AsyncMock(side_effect=RuntimeError("API timeout"))

        enricher = ReferenceStubEnricher(
            bus=fake_bus,
            vault_projects_dir=vault_dir,
            config=fake_config,
            provider=provider,
            enabled=True,
        )

        project_id = "test-project"
        stub_name = "spec-test.md"
        source_path = _create_source_file(tmp_path)
        _create_stub_file(vault_dir, project_id, stub_name)

        result = await enricher.enrich_stub(
            project_id=project_id,
            abs_path=source_path,
            stub_name=stub_name,
        )

        assert result.success is False
        assert "LLM summarization failed" in result.error

    @pytest.mark.asyncio
    async def test_empty_llm_response_fails(self, fake_bus, vault_dir, fake_config, tmp_path):
        provider = AsyncMock()
        provider.create_message = AsyncMock(
            return_value=FakeChatResponse(content=[FakeTextBlock(text="")])
        )

        enricher = ReferenceStubEnricher(
            bus=fake_bus,
            vault_projects_dir=vault_dir,
            config=fake_config,
            provider=provider,
            enabled=True,
        )

        project_id = "test-project"
        stub_name = "spec-test.md"
        source_path = _create_source_file(tmp_path)
        _create_stub_file(vault_dir, project_id, stub_name)

        result = await enricher.enrich_stub(
            project_id=project_id,
            abs_path=source_path,
            stub_name=stub_name,
        )

        assert result.success is False
        assert "empty sections" in result.error


class TestReferenceStubEnricherEventHandler:
    """Tests for the _on_spec_changed event handler."""

    @pytest.mark.asyncio
    async def test_created_event_triggers_enrichment(self, enricher, vault_dir, tmp_path):
        project_id = "test-project"
        stub_name = "spec-orchestrator.md"
        source_path = _create_source_file(tmp_path)
        _create_stub_file(vault_dir, project_id, stub_name)

        event_data = {
            "_event_type": "workspace.spec.changed",
            "project_id": project_id,
            "workspace_path": str(tmp_path / "workspace"),
            "rel_path": "specs/orchestrator.md",
            "abs_path": source_path,
            "operation": "created",
            "content_hash": "abc123def456",
            "stub_name": stub_name,
        }

        await enricher._on_spec_changed(event_data)

        assert enricher.total_enriched == 1

    @pytest.mark.asyncio
    async def test_modified_event_triggers_enrichment(self, enricher, vault_dir, tmp_path):
        project_id = "test-project"
        stub_name = "spec-orchestrator.md"
        source_path = _create_source_file(tmp_path)
        _create_stub_file(vault_dir, project_id, stub_name)

        event_data = {
            "_event_type": "workspace.spec.changed",
            "project_id": project_id,
            "workspace_path": str(tmp_path / "workspace"),
            "rel_path": "specs/orchestrator.md",
            "abs_path": source_path,
            "operation": "modified",
            "content_hash": "abc123def456",
            "stub_name": stub_name,
        }

        await enricher._on_spec_changed(event_data)

        assert enricher.total_enriched == 1

    @pytest.mark.asyncio
    async def test_deleted_event_is_ignored(self, enricher):
        event_data = {
            "_event_type": "workspace.spec.changed",
            "project_id": "test-project",
            "workspace_path": "/workspace",
            "rel_path": "specs/orchestrator.md",
            "abs_path": "/workspace/specs/orchestrator.md",
            "operation": "deleted",
            "content_hash": "",
            "stub_name": "spec-orchestrator.md",
        }

        await enricher._on_spec_changed(event_data)

        assert enricher.total_enriched == 0
        assert enricher.total_failed == 0

    @pytest.mark.asyncio
    async def test_disabled_enricher_ignores_events(self, enricher, vault_dir, tmp_path):
        enricher.enabled = False

        event_data = {
            "_event_type": "workspace.spec.changed",
            "project_id": "test-project",
            "abs_path": _create_source_file(tmp_path),
            "operation": "created",
            "stub_name": "spec-test.md",
        }

        await enricher._on_spec_changed(event_data)

        assert enricher.total_enriched == 0

    @pytest.mark.asyncio
    async def test_incomplete_event_data_logged(self, enricher):
        """Events with missing required fields should be skipped gracefully."""
        event_data = {
            "_event_type": "workspace.spec.changed",
            "project_id": "test-project",
            # Missing abs_path and stub_name
            "operation": "created",
        }

        await enricher._on_spec_changed(event_data)

        assert enricher.total_enriched == 0
        assert enricher.total_failed == 0


class TestReferenceStubEnricherReadSource:
    """Tests for source file reading and truncation."""

    def test_reads_normal_file(self, enricher, tmp_path):
        source = tmp_path / "test.md"
        source.write_text("# Hello\nWorld", encoding="utf-8")
        content = enricher._read_source(str(source))
        assert content == "# Hello\nWorld"

    def test_truncates_large_file(self, tmp_path, fake_bus, fake_config, fake_provider):
        vault_dir = str(tmp_path / "vault")
        enricher = ReferenceStubEnricher(
            bus=fake_bus,
            vault_projects_dir=vault_dir,
            config=fake_config,
            provider=fake_provider,
            max_source_chars=100,
        )

        source = tmp_path / "large.md"
        source.write_text("x" * 500, encoding="utf-8")
        content = enricher._read_source(str(source))

        assert len(content) > 100  # includes truncation note
        assert "[Document truncated at 100 characters" in content

    def test_missing_file_returns_empty(self, enricher):
        content = enricher._read_source("/nonexistent/file.md")
        assert content == ""

    def test_empty_file_returns_empty(self, enricher, tmp_path):
        source = tmp_path / "empty.md"
        source.write_text("", encoding="utf-8")
        content = enricher._read_source(str(source))
        assert content == ""

    def test_whitespace_only_file_returns_empty(self, enricher, tmp_path):
        source = tmp_path / "whitespace.md"
        source.write_text("   \n\n  \t  ", encoding="utf-8")
        content = enricher._read_source(str(source))
        assert content == ""


class TestReferenceStubEnricherSummarize:
    """Tests for the _summarize_document method."""

    @pytest.mark.asyncio
    async def test_sends_correct_prompt_to_llm(self, enricher, fake_provider):
        content = "# Test Doc\nSome content here."
        await enricher._summarize_document(fake_provider, content)

        fake_provider.create_message.assert_called_once()
        call_kwargs = fake_provider.create_message.call_args.kwargs
        assert call_kwargs["system"] == SUMMARIZE_SYSTEM_PROMPT
        # max_tokens default was bumped from 1024 → 2048.
        assert call_kwargs["max_tokens"] == 2048
        messages = call_kwargs["messages"]
        assert len(messages) == 1
        assert messages[0]["role"] == "user"
        assert "# Test Doc" in messages[0]["content"]
        assert "Some content here." in messages[0]["content"]

    @pytest.mark.asyncio
    async def test_empty_text_parts_returns_empty_sections(self, enricher):
        provider = AsyncMock()
        provider.create_message = AsyncMock(return_value=FakeChatResponse(content=[]))
        result = await enricher._summarize_document(provider, "some content")
        assert result["summary"] == ""
        assert result["key_decisions"] == ""
        assert result["key_interfaces"] == ""


class TestReferenceStubEnricherProviderFallback:
    """Tests for LLM provider fallback chain."""

    def test_uses_injected_provider(self, enricher, fake_provider):
        result = enricher._get_provider()
        assert result is fake_provider

    def test_creates_provider_from_config(self, fake_bus, fake_config, tmp_path):
        enricher = ReferenceStubEnricher(
            bus=fake_bus,
            vault_projects_dir=str(tmp_path),
            config=fake_config,
            provider=None,
            enabled=True,
        )

        mock_provider = MagicMock()
        with patch(
            "src.chat_providers.create_chat_provider",
            return_value=mock_provider,
        ) as mock_create:
            result = enricher._get_provider()
            assert result is mock_provider
            mock_create.assert_called_once()

    def test_fallback_to_revision_provider(self, fake_bus, tmp_path):
        @dataclass
        class Config:
            stub_enrichment_enabled: bool = True
            stub_enrichment_provider: str = ""
            stub_enrichment_model: str = ""
            stub_enrichment_max_source_chars: int = 20_000
            revision_provider: str = "ollama"
            revision_model: str = "qwen:7b"

        enricher = ReferenceStubEnricher(
            bus=fake_bus,
            vault_projects_dir=str(tmp_path),
            config=Config(),
            provider=None,
            enabled=True,
        )

        with patch("src.chat_providers.create_chat_provider") as mock_create:
            mock_create.return_value = MagicMock()
            enricher._get_provider()
            call_args = mock_create.call_args[0][0]
            assert call_args.provider == "ollama"
            assert call_args.model == "qwen:7b"

    def test_stub_enrichment_provider_takes_precedence(self, fake_bus, tmp_path):
        @dataclass
        class Config:
            stub_enrichment_enabled: bool = True
            stub_enrichment_provider: str = "gemini"
            stub_enrichment_model: str = "gemini-2.5-flash"
            stub_enrichment_max_source_chars: int = 20_000
            revision_provider: str = "ollama"
            revision_model: str = "qwen:7b"

        enricher = ReferenceStubEnricher(
            bus=fake_bus,
            vault_projects_dir=str(tmp_path),
            config=Config(),
            provider=None,
            enabled=True,
        )

        with patch("src.chat_providers.create_chat_provider") as mock_create:
            mock_create.return_value = MagicMock()
            enricher._get_provider()
            call_args = mock_create.call_args[0][0]
            assert call_args.provider == "gemini"
            assert call_args.model == "gemini-2.5-flash"


class TestReferenceStubEnricherLargeFiles:
    """Tests for handling large spec files (>5000 tokens, per roadmap 6.3.5f)."""

    @pytest.mark.asyncio
    async def test_large_file_truncated_but_enriched(
        self, vault_dir, fake_bus, fake_config, tmp_path
    ):
        """Stub generation handles large spec files by truncating and summarizing."""
        # Set a small limit for testing
        fake_config.stub_enrichment_max_source_chars = 500

        provider = AsyncMock()
        provider.create_message = AsyncMock(
            return_value=FakeChatResponse(
                content=[
                    FakeTextBlock(
                        text=(
                            "## Summary\n"
                            "A very large specification document.\n\n"
                            "## Key Decisions\n"
                            "- Large-scale architecture\n\n"
                            "## Key Interfaces\n"
                            "- Main API surface"
                        )
                    )
                ]
            )
        )

        enricher = ReferenceStubEnricher(
            bus=fake_bus,
            vault_projects_dir=vault_dir,
            config=fake_config,
            provider=provider,
            enabled=True,
            max_source_chars=500,
        )

        # Create a large source file
        source = tmp_path / "workspace" / "specs" / "big-spec.md"
        source.parent.mkdir(parents=True, exist_ok=True)
        source.write_text("# Big Spec\n" + "Content line.\n" * 1000, encoding="utf-8")

        project_id = "test-project"
        stub_name = "spec-big-spec.md"
        _create_stub_file(vault_dir, project_id, stub_name)

        result = await enricher.enrich_stub(
            project_id=project_id,
            abs_path=str(source),
            stub_name=stub_name,
        )

        assert result.success is True
        # Verify the LLM received truncated content
        call_kwargs = provider.create_message.call_args.kwargs
        user_msg = call_kwargs["messages"][0]["content"]
        assert "[Document truncated at 500 characters" in user_msg


class TestReferenceStubEnricherMultipleFiles:
    """Tests for handling multiple files."""

    @pytest.mark.asyncio
    async def test_multiple_enrichments_increment_counter(self, enricher, vault_dir, tmp_path):
        """Multiple spec files changed simultaneously each get enriched."""
        for name in ["orchestrator", "database", "supervisor"]:
            source = tmp_path / "workspace" / "specs" / f"{name}.md"
            source.parent.mkdir(parents=True, exist_ok=True)
            source.write_text(f"# {name.title()} Spec\nContent about {name}.", encoding="utf-8")

            stub_name = f"spec-{name}.md"
            _create_stub_file(vault_dir, "test-project", stub_name)

            result = await enricher.enrich_stub(
                project_id="test-project",
                abs_path=str(source),
                stub_name=stub_name,
            )
            assert result.success is True

        assert enricher.total_enriched == 3
        assert enricher.total_failed == 0


class TestReferenceStubEnricherStubFormat:
    """Tests verifying enriched stubs maintain Obsidian-compatible format."""

    @pytest.mark.asyncio
    async def test_enriched_stub_retains_frontmatter(self, enricher, vault_dir, tmp_path):
        project_id = "test-project"
        stub_name = "spec-orchestrator.md"
        source_path = _create_source_file(tmp_path)
        stub_path = _create_stub_file(vault_dir, project_id, stub_name)

        await enricher.enrich_stub(
            project_id=project_id,
            abs_path=source_path,
            stub_name=stub_name,
        )

        with open(stub_path, encoding="utf-8") as f:
            content = f.read()

        # Frontmatter must be preserved
        assert content.startswith("---\n")
        assert "tags: [spec, reference, auto-generated]" in content
        assert "source:" in content
        assert "source_hash:" in content
        assert "last_synced:" in content

    @pytest.mark.asyncio
    async def test_enriched_stub_retains_excerpt(self, enricher, vault_dir, tmp_path):
        project_id = "test-project"
        stub_name = "spec-orchestrator.md"
        source_path = _create_source_file(tmp_path)
        stub_path = _create_stub_file(vault_dir, project_id, stub_name)

        await enricher.enrich_stub(
            project_id=project_id,
            abs_path=source_path,
            stub_name=stub_name,
        )

        with open(stub_path, encoding="utf-8") as f:
            content = f.read()

        # Excerpt section must be preserved
        assert "## Excerpt" in content

    @pytest.mark.asyncio
    async def test_enriched_stub_has_all_sections(self, enricher, vault_dir, tmp_path):
        project_id = "test-project"
        stub_name = "spec-orchestrator.md"
        source_path = _create_source_file(tmp_path)
        stub_path = _create_stub_file(vault_dir, project_id, stub_name)

        await enricher.enrich_stub(
            project_id=project_id,
            abs_path=source_path,
            stub_name=stub_name,
        )

        with open(stub_path, encoding="utf-8") as f:
            content = f.read()

        # All expected sections must be present
        assert "## Excerpt" in content
        assert "## Summary" in content
        assert "## Key Decisions" in content
        assert "## Key Interfaces" in content


# ---------------------------------------------------------------------------
# extract_source_hash_from_frontmatter tests (6.3.3)
# ---------------------------------------------------------------------------


class TestExtractSourceHashFromFrontmatter:
    """Tests for the extract_source_hash_from_frontmatter() function."""

    def test_extracts_hash_from_valid_frontmatter(self):
        content = (
            "---\n"
            "tags: [spec, reference, auto-generated]\n"
            "source: /workspace/specs/orchestrator.md\n"
            "source_hash: abc123def456\n"
            "last_synced: 2026-04-07\n"
            "---\n\n"
            "# Spec: Orchestrator\n"
        )
        assert extract_source_hash_from_frontmatter(content) == "abc123def456"

    def test_returns_empty_for_no_frontmatter(self):
        content = "# Just a heading\n\nSome content."
        assert extract_source_hash_from_frontmatter(content) == ""

    def test_returns_empty_for_empty_content(self):
        assert extract_source_hash_from_frontmatter("") == ""

    def test_returns_empty_for_missing_source_hash(self):
        content = "---\ntags: [spec]\nsource: /foo\nlast_synced: 2026-04-07\n---\n\n# Content\n"
        assert extract_source_hash_from_frontmatter(content) == ""

    def test_handles_quoted_hash(self):
        content = '---\nsource_hash: "abc123def456"\n---\n\nContent\n'
        assert extract_source_hash_from_frontmatter(content) == "abc123def456"

    def test_handles_single_quoted_hash(self):
        content = "---\nsource_hash: 'abc123def456'\n---\n\nContent\n"
        assert extract_source_hash_from_frontmatter(content) == "abc123def456"

    def test_returns_empty_for_unclosed_frontmatter(self):
        content = "---\nsource_hash: abc123def456\n# No closing ---"
        assert extract_source_hash_from_frontmatter(content) == ""

    def test_handles_extra_whitespace(self):
        content = "---\n  source_hash:   abc123def456  \n---\n\n"
        assert extract_source_hash_from_frontmatter(content) == "abc123def456"


# ---------------------------------------------------------------------------
# stub_is_enriched tests (6.3.3)
# ---------------------------------------------------------------------------


class TestStubIsEnriched:
    """Tests for the stub_is_enriched() function."""

    def test_placeholder_stub_is_not_enriched(self):
        content = (
            "## Summary\n\n"
            "*Summary pending -- will be generated by LLM enrichment.*\n\n"
            "## Key Decisions\n\n"
            "*Pending LLM extraction.*\n\n"
            "## Key Interfaces\n\n"
            "*Pending LLM extraction.*\n"
        )
        assert stub_is_enriched(content) is False

    def test_enriched_stub_is_detected(self):
        content = (
            "## Summary\n\n"
            "This is a real summary of the document.\n\n"
            "## Key Decisions\n\n"
            "- Real decision one\n"
            "- Real decision two\n\n"
            "## Key Interfaces\n\n"
            "- `real_fn()` -- does stuff\n"
        )
        assert stub_is_enriched(content) is True

    def test_partially_enriched_stub_is_detected(self):
        """If at least one section has real content, stub is enriched."""
        content = (
            "## Summary\n\n"
            "This is a real summary.\n\n"
            "## Key Decisions\n\n"
            "*Pending LLM extraction.*\n\n"
            "## Key Interfaces\n\n"
            "*Pending LLM extraction.*\n"
        )
        assert stub_is_enriched(content) is True

    def test_empty_content_is_not_enriched(self):
        assert stub_is_enriched("") is False

    def test_stub_with_frontmatter_and_placeholders(self):
        content = (
            "---\ntags: [spec]\nsource_hash: abc123\n---\n\n"
            "# Spec: Foo\n\n"
            "## Excerpt\n\nSome excerpt.\n\n"
            "## Summary\n\n"
            "*Summary pending -- will be generated by LLM enrichment.*\n\n"
            "## Key Decisions\n\n"
            "*Pending LLM extraction.*\n\n"
            "## Key Interfaces\n\n"
            "*Pending LLM extraction.*\n"
        )
        assert stub_is_enriched(content) is False

    def test_stub_with_frontmatter_and_real_content(self):
        content = (
            "---\ntags: [spec]\nsource_hash: abc123\n---\n\n"
            "# Spec: Foo\n\n"
            "## Excerpt\n\nSome excerpt.\n\n"
            "## Summary\n\n"
            "A real summary of the document.\n\n"
            "## Key Decisions\n\n"
            "- Decision A\n\n"
            "## Key Interfaces\n\n"
            "- `Interface.foo()` -- entry point\n"
        )
        assert stub_is_enriched(content) is True


# ---------------------------------------------------------------------------
# Source hash skip logic tests (6.3.3)
# ---------------------------------------------------------------------------


class TestSourceHashSkipEnrichment:
    """Tests for source_hash-based skip logic in enrich_stub() (Roadmap 6.3.3)."""

    @pytest.mark.asyncio
    async def test_unchanged_hash_enriched_stub_is_skipped(self, enricher, vault_dir, tmp_path):
        """Unchanged source + already-enriched stub → skip LLM call."""
        project_id = "test-project"
        stub_name = "spec-orchestrator.md"
        source_path = _create_source_file(tmp_path)

        # Compute the real hash of the source file
        from src.workspace_spec_watcher import compute_content_hash

        real_hash = compute_content_hash(source_path)

        # Create an enriched stub with the matching hash
        _create_enriched_stub_file(vault_dir, project_id, stub_name, source_hash=real_hash)

        result = await enricher.enrich_stub(
            project_id=project_id,
            abs_path=source_path,
            stub_name=stub_name,
            content_hash=real_hash,
        )

        assert result.success is True
        assert result.skipped is True
        assert enricher.total_skipped == 1
        assert enricher.total_enriched == 0
        # LLM should NOT have been called
        enricher._provider.create_message.assert_not_called()

    @pytest.mark.asyncio
    async def test_unchanged_hash_placeholder_stub_is_enriched(self, enricher, vault_dir, tmp_path):
        """Unchanged source + placeholder stub → must still enrich."""
        project_id = "test-project"
        stub_name = "spec-orchestrator.md"
        source_path = _create_source_file(tmp_path)

        from src.workspace_spec_watcher import compute_content_hash

        real_hash = compute_content_hash(source_path)

        # Create a placeholder stub with the matching hash
        _create_stub_file(vault_dir, project_id, stub_name)
        # Patch stub to have the correct hash
        stub_path = os.path.join(vault_dir, project_id, "references", stub_name)
        with open(stub_path, encoding="utf-8") as f:
            content = f.read()
        content = content.replace("abc123def456", real_hash)
        with open(stub_path, "w", encoding="utf-8") as f:
            f.write(content)

        result = await enricher.enrich_stub(
            project_id=project_id,
            abs_path=source_path,
            stub_name=stub_name,
            content_hash=real_hash,
        )

        assert result.success is True
        assert result.skipped is False
        assert enricher.total_enriched == 1
        assert enricher.total_skipped == 0
        # LLM SHOULD have been called
        enricher._provider.create_message.assert_called_once()

    @pytest.mark.asyncio
    async def test_changed_hash_enriched_stub_is_re_enriched(self, enricher, vault_dir, tmp_path):
        """Changed source hash → must re-enrich even if stub is already enriched."""
        project_id = "test-project"
        stub_name = "spec-orchestrator.md"
        source_path = _create_source_file(tmp_path)

        # Create enriched stub with a DIFFERENT hash
        _create_enriched_stub_file(vault_dir, project_id, stub_name, source_hash="oldhash12345")

        result = await enricher.enrich_stub(
            project_id=project_id,
            abs_path=source_path,
            stub_name=stub_name,
            content_hash="newhash67890",
        )

        assert result.success is True
        assert result.skipped is False
        assert enricher.total_enriched == 1
        assert enricher.total_skipped == 0

    @pytest.mark.asyncio
    async def test_force_bypasses_hash_check(self, enricher, vault_dir, tmp_path):
        """force=True always re-enriches, even if hash matches."""
        project_id = "test-project"
        stub_name = "spec-orchestrator.md"
        source_path = _create_source_file(tmp_path)

        from src.workspace_spec_watcher import compute_content_hash

        real_hash = compute_content_hash(source_path)

        # Create enriched stub with matching hash
        _create_enriched_stub_file(vault_dir, project_id, stub_name, source_hash=real_hash)

        result = await enricher.enrich_stub(
            project_id=project_id,
            abs_path=source_path,
            stub_name=stub_name,
            content_hash=real_hash,
            force=True,
        )

        assert result.success is True
        assert result.skipped is False
        assert enricher.total_enriched == 1
        assert enricher.total_skipped == 0
        # LLM SHOULD have been called despite matching hash
        enricher._provider.create_message.assert_called_once()

    @pytest.mark.asyncio
    async def test_missing_stub_file_not_skipped(self, enricher, vault_dir, tmp_path):
        """No stub file → enrichment proceeds (and fails with 'stub not found')."""
        project_id = "test-project"
        stub_name = "spec-nonexistent.md"
        source_path = _create_source_file(tmp_path)

        result = await enricher.enrich_stub(
            project_id=project_id,
            abs_path=source_path,
            stub_name=stub_name,
            content_hash="somehash12345",
        )

        # Enrichment should proceed (not skip), but fail because stub file is missing
        assert result.skipped is False
        assert result.success is False
        assert "Stub file not found" in result.error

    @pytest.mark.asyncio
    async def test_no_hash_in_stub_not_skipped(self, enricher, vault_dir, tmp_path):
        """Stub without source_hash in frontmatter → must enrich."""
        project_id = "test-project"
        stub_name = "spec-nohash.md"
        source_path = _create_source_file(tmp_path)

        # Create a stub with no source_hash
        refs_dir = os.path.join(vault_dir, project_id, "references")
        os.makedirs(refs_dir, exist_ok=True)
        stub_path = os.path.join(refs_dir, stub_name)
        content = (
            "---\n"
            "tags: [spec, reference, auto-generated]\n"
            "source: /workspace/specs/orchestrator.md\n"
            "last_synced: 2026-04-07\n"
            "---\n\n"
            "# Spec: Orchestrator\n\n"
            "## Excerpt\n\nFirst few lines.\n\n"
            "## Summary\n\n"
            "Already enriched summary.\n\n"
            "## Key Decisions\n\n"
            "- Decision A\n\n"
            "## Key Interfaces\n\n"
            "- Interface A\n"
        )
        with open(stub_path, "w", encoding="utf-8") as f:
            f.write(content)

        result = await enricher.enrich_stub(
            project_id=project_id,
            abs_path=source_path,
            stub_name=stub_name,
            content_hash="somehash12345",
        )

        assert result.skipped is False
        assert result.success is True
        assert enricher.total_enriched == 1

    @pytest.mark.asyncio
    async def test_computes_hash_when_not_provided(self, enricher, vault_dir, tmp_path):
        """When content_hash is empty, enricher computes it from the source file."""
        project_id = "test-project"
        stub_name = "spec-orchestrator.md"
        source_path = _create_source_file(tmp_path)

        from src.workspace_spec_watcher import compute_content_hash

        real_hash = compute_content_hash(source_path)

        # Create enriched stub with matching hash
        _create_enriched_stub_file(vault_dir, project_id, stub_name, source_hash=real_hash)

        # Do NOT pass content_hash — enricher should compute it
        result = await enricher.enrich_stub(
            project_id=project_id,
            abs_path=source_path,
            stub_name=stub_name,
        )

        assert result.success is True
        assert result.skipped is True
        assert enricher.total_skipped == 1

    @pytest.mark.asyncio
    async def test_total_skipped_increments_correctly(self, enricher, vault_dir, tmp_path):
        """Multiple skips increment the counter correctly."""
        project_id = "test-project"
        source_path = _create_source_file(tmp_path)

        from src.workspace_spec_watcher import compute_content_hash

        real_hash = compute_content_hash(source_path)

        for name in ["spec-one.md", "spec-two.md", "spec-three.md"]:
            _create_enriched_stub_file(vault_dir, project_id, name, source_hash=real_hash)

            result = await enricher.enrich_stub(
                project_id=project_id,
                abs_path=source_path,
                stub_name=name,
                content_hash=real_hash,
            )
            assert result.skipped is True

        assert enricher.total_skipped == 3
        assert enricher.total_enriched == 0

    @pytest.mark.asyncio
    async def test_skipped_result_has_correct_fields(self, enricher, vault_dir, tmp_path):
        """Skipped EnrichmentResult has expected field values."""
        project_id = "test-project"
        stub_name = "spec-orchestrator.md"
        source_path = _create_source_file(tmp_path)

        from src.workspace_spec_watcher import compute_content_hash

        real_hash = compute_content_hash(source_path)
        _create_enriched_stub_file(vault_dir, project_id, stub_name, source_hash=real_hash)

        result = await enricher.enrich_stub(
            project_id=project_id,
            abs_path=source_path,
            stub_name=stub_name,
            content_hash=real_hash,
        )

        assert result.project_id == project_id
        assert result.stub_name == stub_name
        assert result.success is True
        assert result.skipped is True
        assert result.summary == ""
        assert result.key_decisions == ""
        assert result.key_interfaces == ""
        assert result.error == ""


class TestSourceHashEventHandler:
    """Tests for hash-based skip in the _on_spec_changed event handler."""

    @pytest.mark.asyncio
    async def test_event_with_matching_hash_skips_enrichment(self, enricher, vault_dir, tmp_path):
        """Event carrying a content_hash that matches the stub skips LLM."""
        project_id = "test-project"
        stub_name = "spec-orchestrator.md"
        source_path = _create_source_file(tmp_path)

        from src.workspace_spec_watcher import compute_content_hash

        real_hash = compute_content_hash(source_path)
        _create_enriched_stub_file(vault_dir, project_id, stub_name, source_hash=real_hash)

        event_data = {
            "_event_type": "workspace.spec.changed",
            "project_id": project_id,
            "workspace_path": str(tmp_path / "workspace"),
            "rel_path": "specs/orchestrator.md",
            "abs_path": source_path,
            "operation": "modified",
            "content_hash": real_hash,
            "stub_name": stub_name,
        }

        await enricher._on_spec_changed(event_data)

        assert enricher.total_skipped == 1
        assert enricher.total_enriched == 0
        enricher._provider.create_message.assert_not_called()

    @pytest.mark.asyncio
    async def test_event_with_changed_hash_enriches(self, enricher, vault_dir, tmp_path):
        """Event with a different content_hash triggers re-enrichment."""
        project_id = "test-project"
        stub_name = "spec-orchestrator.md"
        source_path = _create_source_file(tmp_path)

        # Stub has old hash
        _create_enriched_stub_file(vault_dir, project_id, stub_name, source_hash="oldhash12345")

        event_data = {
            "_event_type": "workspace.spec.changed",
            "project_id": project_id,
            "workspace_path": str(tmp_path / "workspace"),
            "rel_path": "specs/orchestrator.md",
            "abs_path": source_path,
            "operation": "modified",
            "content_hash": "newhash67890",
            "stub_name": stub_name,
        }

        await enricher._on_spec_changed(event_data)

        assert enricher.total_enriched == 1
        assert enricher.total_skipped == 0


class TestSourceHashTouchWithoutContentChange:
    """Test that touching a file without changing content does NOT regenerate.

    This corresponds to Roadmap 6.3.6(b): touching file without content change
    does NOT trigger regeneration.
    """

    @pytest.mark.asyncio
    async def test_touch_without_content_change_skipped(self, enricher, vault_dir, tmp_path):
        """mtime changes but content hash stays the same → skip."""
        project_id = "test-project"
        stub_name = "spec-orchestrator.md"
        source_path = _create_source_file(tmp_path)

        from src.workspace_spec_watcher import compute_content_hash

        real_hash = compute_content_hash(source_path)
        _create_enriched_stub_file(vault_dir, project_id, stub_name, source_hash=real_hash)

        # "Touch" the file — update mtime without changing content
        import time

        os.utime(source_path, (time.time() + 100, time.time() + 100))

        # Hash should still match since content didn't change
        new_hash = compute_content_hash(source_path)
        assert new_hash == real_hash

        result = await enricher.enrich_stub(
            project_id=project_id,
            abs_path=source_path,
            stub_name=stub_name,
            content_hash=new_hash,
        )

        assert result.success is True
        assert result.skipped is True


class TestSourceHashPersistence:
    """Test that source_hash persists across enricher instances.

    Corresponds to Roadmap 6.3.6(c): source_hash is persisted across
    system restarts via the stub file's YAML frontmatter.
    """

    @pytest.mark.asyncio
    async def test_hash_persists_across_enricher_instances(
        self, fake_bus, vault_dir, fake_config, fake_provider, tmp_path
    ):
        """New enricher instance still sees the hash from the stub file."""
        project_id = "test-project"
        stub_name = "spec-orchestrator.md"
        source_path = _create_source_file(tmp_path)

        from src.workspace_spec_watcher import compute_content_hash

        real_hash = compute_content_hash(source_path)
        _create_enriched_stub_file(vault_dir, project_id, stub_name, source_hash=real_hash)

        # Create a fresh enricher instance (simulating restart)
        enricher2 = ReferenceStubEnricher(
            bus=fake_bus,
            vault_projects_dir=vault_dir,
            config=fake_config,
            provider=fake_provider,
            enabled=True,
        )

        result = await enricher2.enrich_stub(
            project_id=project_id,
            abs_path=source_path,
            stub_name=stub_name,
            content_hash=real_hash,
        )

        assert result.success is True
        assert result.skipped is True
        assert enricher2.total_skipped == 1


# ---------------------------------------------------------------------------
# Stale stub detection tests (6.3.6d)
# ---------------------------------------------------------------------------


class TestStaleStubDetection:
    """Test stale stub detection when source is manually edited.

    Corresponds to Roadmap 6.3.6(d): manually editing source file without
    triggering watcher flags stub as potentially stale (hash mismatch
    detected by the enricher).
    """

    @pytest.mark.asyncio
    async def test_manual_source_edit_detected_as_stale(self, enricher, vault_dir, tmp_path):
        """Editing source file on disk → hash mismatch → stub re-enriched (not skipped)."""
        project_id = "test-project"
        stub_name = "spec-orchestrator.md"
        source_path = _create_source_file(tmp_path)

        from src.workspace_spec_watcher import compute_content_hash

        original_hash = compute_content_hash(source_path)
        _create_enriched_stub_file(vault_dir, project_id, stub_name, source_hash=original_hash)

        # Manually edit the source file (simulating edit outside the watcher flow)
        with open(source_path, "w", encoding="utf-8") as f:
            f.write("# Orchestrator Spec v2\n\n## Updated Content\nCompletely rewritten.\n")

        # Verify hash actually changed
        new_hash = compute_content_hash(source_path)
        assert new_hash != original_hash

        # Call enrich_stub WITHOUT providing content_hash — enricher must compute it
        result = await enricher.enrich_stub(
            project_id=project_id,
            abs_path=source_path,
            stub_name=stub_name,
        )

        # Should NOT be skipped — stale stub detected via hash mismatch
        assert result.skipped is False
        assert result.success is True
        assert enricher.total_enriched == 1
        assert enricher.total_skipped == 0
        # LLM SHOULD have been called to re-enrich
        enricher._provider.create_message.assert_called_once()

    @pytest.mark.asyncio
    async def test_check_skip_returns_none_on_stale_hash(self, enricher, vault_dir, tmp_path):
        """_check_skip_enrichment returns None when source was manually edited."""
        project_id = "test-project"
        stub_name = "spec-orchestrator.md"
        source_path = _create_source_file(tmp_path)

        from src.workspace_spec_watcher import compute_content_hash

        original_hash = compute_content_hash(source_path)
        stub_path = _create_enriched_stub_file(
            vault_dir, project_id, stub_name, source_hash=original_hash
        )

        # Manually edit source (simulating external edit without watcher)
        with open(source_path, "w", encoding="utf-8") as f:
            f.write("# Completely New Content\n\nThis file was manually changed.\n")

        # _check_skip_enrichment should detect the hash mismatch
        result = enricher._check_skip_enrichment(
            abs_path=source_path,
            stub_path=stub_path,
            content_hash="",  # Force enricher to compute from file
            project_id=project_id,
            stub_name=stub_name,
        )

        # None means "do not skip — proceed with enrichment" (stub is stale)
        assert result is None
        assert enricher.total_skipped == 0

    @pytest.mark.asyncio
    async def test_stale_detection_in_event_flow(self, enricher, vault_dir, tmp_path):
        """Event handler detects stale stub when source changed between events."""
        project_id = "test-project"
        stub_name = "spec-orchestrator.md"
        source_path = _create_source_file(tmp_path)

        from src.workspace_spec_watcher import compute_content_hash

        original_hash = compute_content_hash(source_path)
        _create_enriched_stub_file(vault_dir, project_id, stub_name, source_hash=original_hash)

        # Source was edited; watcher detected the change and sends event with new hash
        with open(source_path, "w", encoding="utf-8") as f:
            f.write("# Orchestrator Spec v2\n\nRewritten content.\n")
        new_hash = compute_content_hash(source_path)
        assert new_hash != original_hash

        event_data = {
            "_event_type": "workspace.spec.changed",
            "project_id": project_id,
            "workspace_path": str(tmp_path / "workspace"),
            "rel_path": "specs/orchestrator.md",
            "abs_path": source_path,
            "operation": "modified",
            "content_hash": new_hash,
            "stub_name": stub_name,
        }

        await enricher._on_spec_changed(event_data)

        # Stale detected → LLM called for re-enrichment
        assert enricher.total_enriched == 1
        assert enricher.total_skipped == 0
        enricher._provider.create_message.assert_called_once()


# ---------------------------------------------------------------------------
# Deleted source / orphaned stub tests (6.3.6f)
# ---------------------------------------------------------------------------


class TestDeletedSourceOrphanedStub:
    """Test stub orphan handling when source file is deleted.

    Corresponds to Roadmap 6.3.6(f): deleting source file flags
    corresponding stub as orphaned.
    """

    @pytest.mark.asyncio
    async def test_deleted_source_fails_enrichment(self, enricher, vault_dir, tmp_path):
        """Enrichment fails gracefully when source file has been deleted."""
        project_id = "test-project"
        stub_name = "spec-orchestrator.md"
        source_path = _create_source_file(tmp_path)

        from src.workspace_spec_watcher import compute_content_hash

        real_hash = compute_content_hash(source_path)
        _create_enriched_stub_file(vault_dir, project_id, stub_name, source_hash=real_hash)

        # Delete the source file (simulating user removing the spec)
        os.remove(source_path)

        result = await enricher.enrich_stub(
            project_id=project_id,
            abs_path=source_path,
            stub_name=stub_name,
        )

        # Should NOT be skipped — hash can't be computed for deleted file
        assert result.skipped is False
        # Enrichment fails because source can't be read
        assert result.success is False
        assert "Could not read source file" in result.error
        assert enricher.total_failed == 1

    @pytest.mark.asyncio
    async def test_deleted_source_hash_returns_empty(self, enricher, vault_dir, tmp_path):
        """compute_content_hash returns '' for deleted file; skip check proceeds."""
        project_id = "test-project"
        stub_name = "spec-orchestrator.md"
        source_path = _create_source_file(tmp_path)

        from src.workspace_spec_watcher import compute_content_hash

        real_hash = compute_content_hash(source_path)
        stub_path = _create_enriched_stub_file(
            vault_dir, project_id, stub_name, source_hash=real_hash
        )

        # Delete the source file
        os.remove(source_path)

        # Hash computation should return empty for non-existent file
        new_hash = compute_content_hash(source_path)
        assert new_hash == ""

        # _check_skip_enrichment should NOT skip (can't verify source hash)
        result = enricher._check_skip_enrichment(
            abs_path=source_path,
            stub_path=stub_path,
            content_hash="",
            project_id=project_id,
            stub_name=stub_name,
        )

        # None = proceed with enrichment (can't confirm stub is current)
        assert result is None
        assert enricher.total_skipped == 0

    @pytest.mark.asyncio
    async def test_deleted_event_ignored_by_enricher(self, enricher, vault_dir, tmp_path):
        """Enricher ignores 'deleted' events — watcher handles stub removal."""
        project_id = "test-project"
        stub_name = "spec-orchestrator.md"
        source_path = _create_source_file(tmp_path)

        from src.workspace_spec_watcher import compute_content_hash

        real_hash = compute_content_hash(source_path)
        _create_enriched_stub_file(vault_dir, project_id, stub_name, source_hash=real_hash)

        event_data = {
            "_event_type": "workspace.spec.changed",
            "project_id": project_id,
            "workspace_path": str(tmp_path / "workspace"),
            "rel_path": "specs/orchestrator.md",
            "abs_path": source_path,
            "operation": "deleted",
            "content_hash": "",
            "stub_name": stub_name,
        }

        await enricher._on_spec_changed(event_data)

        # Enricher should not attempt to enrich deleted files
        assert enricher.total_enriched == 0
        assert enricher.total_skipped == 0
        assert enricher.total_failed == 0
        enricher._provider.create_message.assert_not_called()

    @pytest.mark.asyncio
    async def test_watcher_removes_stub_on_source_deletion(self, tmp_path):
        """WorkspaceSpecWatcher removes the stub file when source is deleted."""
        from src.workspace_spec_watcher import (
            SpecChange,
            WorkspaceSpecWatcher,
            compute_content_hash,
        )

        # Setup vault and watcher
        vault_dir = str(tmp_path / "vault" / "projects")
        os.makedirs(vault_dir, exist_ok=True)

        fake_bus = MagicMock()
        fake_bus.emit = AsyncMock()
        fake_db = MagicMock()
        fake_git = MagicMock()

        watcher = WorkspaceSpecWatcher(
            db=fake_db,
            bus=fake_bus,
            git=fake_git,
            vault_projects_dir=vault_dir,
        )

        # Create workspace with a spec file
        ws = str(tmp_path / "workspace")
        os.makedirs(os.path.join(ws, "specs"), exist_ok=True)
        spec_file = os.path.join(ws, "specs", "orchestrator.md")
        with open(spec_file, "w", encoding="utf-8") as f:
            f.write("# Orchestrator Spec\n\nContent here.\n")

        # Write a stub via watcher
        change = SpecChange(
            project_id="test-project",
            workspace_path=ws,
            rel_path="specs/orchestrator.md",
            abs_path=spec_file,
            operation="created",
            content_hash=compute_content_hash(spec_file),
        )
        stub_path = watcher._write_stub(change)
        assert stub_path is not None
        assert os.path.isfile(stub_path)

        # Delete the source file
        os.remove(spec_file)

        # Watcher detects deletion and removes the orphaned stub
        delete_change = SpecChange(
            project_id="test-project",
            workspace_path=ws,
            rel_path="specs/orchestrator.md",
            abs_path=spec_file,
            operation="deleted",
            content_hash="",
        )
        deleted = watcher._delete_stub(delete_change)
        assert deleted is True
        assert not os.path.isfile(stub_path)
        assert watcher.total_stubs_deleted == 1


# ---------------------------------------------------------------------------
# extract_source_path_from_frontmatter tests (6.3.4)
# ---------------------------------------------------------------------------


class TestExtractSourcePathFromFrontmatter:
    """Tests for the extract_source_path_from_frontmatter() function."""

    def test_extracts_path_from_valid_frontmatter(self):
        content = (
            "---\n"
            "tags: [spec, reference, auto-generated]\n"
            "source: /workspace/specs/orchestrator.md\n"
            "source_hash: abc123def456\n"
            "last_synced: 2026-04-07\n"
            "---\n\n"
            "# Spec: Orchestrator\n"
        )
        assert extract_source_path_from_frontmatter(content) == "/workspace/specs/orchestrator.md"

    def test_returns_empty_for_no_frontmatter(self):
        content = "# Just a heading\n\nSome content."
        assert extract_source_path_from_frontmatter(content) == ""

    def test_returns_empty_for_empty_content(self):
        assert extract_source_path_from_frontmatter("") == ""

    def test_returns_empty_for_missing_source(self):
        content = "---\ntags: [spec]\nsource_hash: abc123\nlast_synced: 2026-04-07\n---\n\n"
        assert extract_source_path_from_frontmatter(content) == ""

    def test_handles_quoted_path(self):
        content = '---\nsource: "/path/with spaces/file.md"\n---\n\nContent\n'
        assert extract_source_path_from_frontmatter(content) == "/path/with spaces/file.md"

    def test_handles_single_quoted_path(self):
        content = "---\nsource: '/path/to/file.md'\n---\n\nContent\n"
        assert extract_source_path_from_frontmatter(content) == "/path/to/file.md"

    def test_returns_empty_for_unclosed_frontmatter(self):
        content = "---\nsource: /path/to/file.md\n# No closing ---"
        assert extract_source_path_from_frontmatter(content) == ""

    def test_handles_extra_whitespace(self):
        content = "---\n  source:   /path/to/file.md  \n---\n\n"
        assert extract_source_path_from_frontmatter(content) == "/path/to/file.md"

    def test_does_not_match_source_hash(self):
        """Ensure 'source:' does not accidentally match 'source_hash:'."""
        content = "---\nsource_hash: abc123\n---\n\n"
        assert extract_source_path_from_frontmatter(content) == ""


# ---------------------------------------------------------------------------
# extract_last_synced_from_frontmatter tests (6.3.4)
# ---------------------------------------------------------------------------


class TestExtractLastSyncedFromFrontmatter:
    """Tests for the extract_last_synced_from_frontmatter() function."""

    def test_extracts_date_from_valid_frontmatter(self):
        content = (
            "---\n"
            "source: /workspace/specs/orchestrator.md\n"
            "source_hash: abc123def456\n"
            "last_synced: 2026-04-07\n"
            "---\n\n"
        )
        assert extract_last_synced_from_frontmatter(content) == "2026-04-07"

    def test_returns_empty_for_no_frontmatter(self):
        content = "# Just a heading\n"
        assert extract_last_synced_from_frontmatter(content) == ""

    def test_returns_empty_for_empty_content(self):
        assert extract_last_synced_from_frontmatter("") == ""

    def test_returns_empty_for_missing_field(self):
        content = "---\nsource: /foo\nsource_hash: abc123\n---\n\n"
        assert extract_last_synced_from_frontmatter(content) == ""

    def test_handles_quoted_date(self):
        content = '---\nlast_synced: "2026-04-07"\n---\n\n'
        assert extract_last_synced_from_frontmatter(content) == "2026-04-07"

    def test_handles_extra_whitespace(self):
        content = "---\n  last_synced:   2026-04-07  \n---\n\n"
        assert extract_last_synced_from_frontmatter(content) == "2026-04-07"


# ---------------------------------------------------------------------------
# scan_stale_stubs tests (Roadmap 6.3.4)
# ---------------------------------------------------------------------------


class TestScanStaleStubs:
    """Tests for scan_stale_stubs() — the main stale stub detection scanner."""

    def test_empty_project_returns_empty_result(self, tmp_path):
        """Project with no references/ directory returns empty scan."""
        vault_dir = str(tmp_path / "vault" / "projects")
        os.makedirs(vault_dir, exist_ok=True)

        result = scan_stale_stubs(vault_dir, "nonexistent-project")

        assert result.project_id == "nonexistent-project"
        assert result.total == 0
        assert result.stubs == []

    def test_empty_references_dir(self, tmp_path):
        """Project with empty references/ directory returns empty scan."""
        vault_dir = str(tmp_path / "vault" / "projects")
        refs_dir = os.path.join(vault_dir, "test-project", "references")
        os.makedirs(refs_dir, exist_ok=True)

        result = scan_stale_stubs(vault_dir, "test-project")

        assert result.total == 0
        assert result.stubs == []

    def test_current_stub_detected(self, tmp_path):
        """Stub with matching source_hash and enriched content → current."""
        vault_dir = str(tmp_path / "vault" / "projects")
        source_path = str(tmp_path / "workspace" / "specs" / "orchestrator.md")
        os.makedirs(os.path.dirname(source_path), exist_ok=True)
        with open(source_path, "w", encoding="utf-8") as f:
            f.write("# Orchestrator Spec\n\nContent here.\n")

        from src.workspace_spec_watcher import compute_content_hash

        real_hash = compute_content_hash(source_path)

        # Create enriched stub pointing to the real source with matching hash
        refs_dir = os.path.join(vault_dir, "test-project", "references")
        os.makedirs(refs_dir, exist_ok=True)
        stub_path = os.path.join(refs_dir, "spec-orchestrator.md")
        content = (
            f"---\n"
            f"tags: [spec, reference, auto-generated]\n"
            f"source: {source_path}\n"
            f"source_hash: {real_hash}\n"
            f"last_synced: 2026-04-07\n"
            f"---\n\n"
            f"# Spec: Orchestrator\n\n"
            f"## Summary\n\n"
            f"A real summary of the document.\n\n"
            f"## Key Decisions\n\n"
            f"- Decision one\n\n"
            f"## Key Interfaces\n\n"
            f"- Interface one\n"
        )
        with open(stub_path, "w", encoding="utf-8") as f:
            f.write(content)

        result = scan_stale_stubs(vault_dir, "test-project")

        assert result.total == 1
        assert result.current == 1
        assert result.stale == 0
        assert result.stubs[0].status == "current"
        assert result.stubs[0].stub_name == "spec-orchestrator.md"
        assert result.stubs[0].recorded_hash == real_hash
        assert result.stubs[0].current_hash == real_hash
        assert result.stubs[0].is_enriched is True

    def test_stale_stub_detected(self, tmp_path):
        """Stub whose source_hash no longer matches → stale."""
        vault_dir = str(tmp_path / "vault" / "projects")
        source_path = str(tmp_path / "workspace" / "specs" / "orchestrator.md")
        os.makedirs(os.path.dirname(source_path), exist_ok=True)
        with open(source_path, "w", encoding="utf-8") as f:
            f.write("# Orchestrator Spec v2\n\nUpdated content.\n")

        # Create enriched stub with an OLD hash
        refs_dir = os.path.join(vault_dir, "test-project", "references")
        os.makedirs(refs_dir, exist_ok=True)
        stub_path = os.path.join(refs_dir, "spec-orchestrator.md")
        content = (
            f"---\n"
            f"tags: [spec, reference, auto-generated]\n"
            f"source: {source_path}\n"
            f"source_hash: oldhash12345\n"
            f"last_synced: 2026-04-01\n"
            f"---\n\n"
            f"# Spec: Orchestrator\n\n"
            f"## Summary\n\n"
            f"An outdated summary.\n\n"
            f"## Key Decisions\n\n"
            f"- Old decision\n\n"
            f"## Key Interfaces\n\n"
            f"- Old interface\n"
        )
        with open(stub_path, "w", encoding="utf-8") as f:
            f.write(content)

        result = scan_stale_stubs(vault_dir, "test-project")

        assert result.total == 1
        assert result.stale == 1
        assert result.current == 0
        assert result.stubs[0].status == "stale"
        assert result.stubs[0].recorded_hash == "oldhash12345"
        assert result.stubs[0].current_hash != "oldhash12345"

    def test_missing_source_detected(self, tmp_path):
        """Stub pointing to a deleted source file → missing_source."""
        vault_dir = str(tmp_path / "vault" / "projects")
        missing_path = str(tmp_path / "workspace" / "specs" / "deleted.md")

        refs_dir = os.path.join(vault_dir, "test-project", "references")
        os.makedirs(refs_dir, exist_ok=True)
        stub_path = os.path.join(refs_dir, "spec-deleted.md")
        content = (
            f"---\n"
            f"source: {missing_path}\n"
            f"source_hash: abc123def456\n"
            f"last_synced: 2026-04-07\n"
            f"---\n\n"
            f"## Summary\n\n"
            f"A real summary.\n\n"
            f"## Key Decisions\n\n"
            f"- Decision\n\n"
            f"## Key Interfaces\n\n"
            f"- Interface\n"
        )
        with open(stub_path, "w", encoding="utf-8") as f:
            f.write(content)

        result = scan_stale_stubs(vault_dir, "test-project")

        assert result.total == 1
        assert result.missing_source == 1
        assert result.stubs[0].status == "missing_source"
        assert result.stubs[0].current_hash == ""

    def test_unenriched_stub_detected(self, tmp_path):
        """Stub with matching hash but placeholder content → unenriched."""
        vault_dir = str(tmp_path / "vault" / "projects")
        source_path = str(tmp_path / "workspace" / "specs" / "orchestrator.md")
        os.makedirs(os.path.dirname(source_path), exist_ok=True)
        with open(source_path, "w", encoding="utf-8") as f:
            f.write("# Orchestrator Spec\n\nContent.\n")

        from src.workspace_spec_watcher import compute_content_hash

        real_hash = compute_content_hash(source_path)

        refs_dir = os.path.join(vault_dir, "test-project", "references")
        os.makedirs(refs_dir, exist_ok=True)
        stub_path = os.path.join(refs_dir, "spec-orchestrator.md")
        content = (
            f"---\n"
            f"source: {source_path}\n"
            f"source_hash: {real_hash}\n"
            f"last_synced: 2026-04-07\n"
            f"---\n\n"
            f"## Summary\n\n"
            f"*Summary pending -- will be generated by LLM enrichment.*\n\n"
            f"## Key Decisions\n\n"
            f"*Pending LLM extraction.*\n\n"
            f"## Key Interfaces\n\n"
            f"*Pending LLM extraction.*\n"
        )
        with open(stub_path, "w", encoding="utf-8") as f:
            f.write(content)

        result = scan_stale_stubs(vault_dir, "test-project")

        assert result.total == 1
        assert result.unenriched == 1
        assert result.stubs[0].status == "unenriched"
        assert result.stubs[0].is_enriched is False

    def test_orphaned_stub_no_source_path(self, tmp_path):
        """Stub with no source field in frontmatter → orphaned."""
        vault_dir = str(tmp_path / "vault" / "projects")

        refs_dir = os.path.join(vault_dir, "test-project", "references")
        os.makedirs(refs_dir, exist_ok=True)
        stub_path = os.path.join(refs_dir, "spec-mystery.md")
        content = (
            "---\n"
            "tags: [spec]\n"
            "last_synced: 2026-04-07\n"
            "---\n\n"
            "## Summary\n\n"
            "A summary.\n\n"
            "## Key Decisions\n\n"
            "- Decision\n\n"
            "## Key Interfaces\n\n"
            "- Interface\n"
        )
        with open(stub_path, "w", encoding="utf-8") as f:
            f.write(content)

        result = scan_stale_stubs(vault_dir, "test-project")

        assert result.total == 1
        assert result.orphaned == 1
        assert result.stubs[0].status == "orphaned"

    def test_orphaned_stub_no_source_hash(self, tmp_path):
        """Stub with source path but no source_hash → orphaned."""
        vault_dir = str(tmp_path / "vault" / "projects")

        refs_dir = os.path.join(vault_dir, "test-project", "references")
        os.makedirs(refs_dir, exist_ok=True)
        stub_path = os.path.join(refs_dir, "spec-nohash.md")
        content = (
            "---\nsource: /some/path.md\nlast_synced: 2026-04-07\n---\n\n## Summary\n\nContent.\n"
        )
        with open(stub_path, "w", encoding="utf-8") as f:
            f.write(content)

        result = scan_stale_stubs(vault_dir, "test-project")

        assert result.total == 1
        assert result.orphaned == 1
        assert result.stubs[0].status == "orphaned"

    def test_mixed_statuses_across_stubs(self, tmp_path):
        """Multiple stubs with different statuses are all reported correctly."""
        vault_dir = str(tmp_path / "vault" / "projects")
        project_id = "test-project"

        # Source file 1 — current (hash matches, enriched)
        source1 = str(tmp_path / "ws" / "specs" / "current.md")
        os.makedirs(os.path.dirname(source1), exist_ok=True)
        with open(source1, "w", encoding="utf-8") as f:
            f.write("# Current spec\n")

        from src.workspace_spec_watcher import compute_content_hash

        hash1 = compute_content_hash(source1)

        # Source file 2 — stale (hash mismatch)
        source2 = str(tmp_path / "ws" / "specs" / "stale.md")
        with open(source2, "w", encoding="utf-8") as f:
            f.write("# Stale spec — updated content\n")

        refs_dir = os.path.join(vault_dir, project_id, "references")
        os.makedirs(refs_dir, exist_ok=True)

        # Current stub
        with open(os.path.join(refs_dir, "spec-current.md"), "w", encoding="utf-8") as f:
            f.write(
                f"---\nsource: {source1}\nsource_hash: {hash1}\n"
                f"last_synced: 2026-04-07\n---\n\n"
                f"## Summary\n\nReal summary.\n\n"
                f"## Key Decisions\n\n- Decision\n\n"
                f"## Key Interfaces\n\n- Interface\n"
            )

        # Stale stub (old hash)
        with open(os.path.join(refs_dir, "spec-stale.md"), "w", encoding="utf-8") as f:
            f.write(
                f"---\nsource: {source2}\nsource_hash: oldhash00000\n"
                f"last_synced: 2026-03-01\n---\n\n"
                f"## Summary\n\nOld summary.\n\n"
                f"## Key Decisions\n\n- Old decision\n\n"
                f"## Key Interfaces\n\n- Old interface\n"
            )

        # Missing source stub
        missing_path = str(tmp_path / "ws" / "specs" / "gone.md")
        with open(os.path.join(refs_dir, "spec-gone.md"), "w", encoding="utf-8") as f:
            f.write(
                f"---\nsource: {missing_path}\nsource_hash: abc123\n"
                f"last_synced: 2026-04-07\n---\n\n"
                f"## Summary\n\nSummary.\n\n"
                f"## Key Decisions\n\n- D\n\n"
                f"## Key Interfaces\n\n- I\n"
            )

        # Orphaned stub (no source_hash)
        with open(os.path.join(refs_dir, "spec-orphan.md"), "w", encoding="utf-8") as f:
            f.write(
                "---\ntags: [spec]\n---\n\n"
                "## Summary\n\nContent.\n\n"
                "## Key Decisions\n\n- D\n\n"
                "## Key Interfaces\n\n- I\n"
            )

        result = scan_stale_stubs(vault_dir, project_id)

        assert result.total == 4
        assert result.current == 1
        assert result.stale == 1
        assert result.missing_source == 1
        assert result.orphaned == 1
        assert result.unenriched == 0

        statuses = {s.stub_name: s.status for s in result.stubs}
        assert statuses["spec-current.md"] == "current"
        assert statuses["spec-stale.md"] == "stale"
        assert statuses["spec-gone.md"] == "missing_source"
        assert statuses["spec-orphan.md"] == "orphaned"

    def test_stubs_sorted_by_name(self, tmp_path):
        """Stubs are returned sorted alphabetically by stub_name."""
        vault_dir = str(tmp_path / "vault" / "projects")
        refs_dir = os.path.join(vault_dir, "test-project", "references")
        os.makedirs(refs_dir, exist_ok=True)

        for name in ["spec-zebra.md", "spec-alpha.md", "spec-middle.md"]:
            with open(os.path.join(refs_dir, name), "w", encoding="utf-8") as f:
                f.write("---\ntags: [spec]\n---\n\n## Summary\n\nContent.\n")

        result = scan_stale_stubs(vault_dir, "test-project")

        names = [s.stub_name for s in result.stubs]
        assert names == ["spec-alpha.md", "spec-middle.md", "spec-zebra.md"]

    def test_ignores_non_md_files(self, tmp_path):
        """Non-.md files in the references/ directory are ignored."""
        vault_dir = str(tmp_path / "vault" / "projects")
        refs_dir = os.path.join(vault_dir, "test-project", "references")
        os.makedirs(refs_dir, exist_ok=True)

        # Create a .md file and a .txt file
        with open(os.path.join(refs_dir, "spec-valid.md"), "w", encoding="utf-8") as f:
            f.write("---\ntags: [spec]\n---\n\n## Summary\n\nContent.\n")
        with open(os.path.join(refs_dir, "notes.txt"), "w", encoding="utf-8") as f:
            f.write("some notes")
        with open(os.path.join(refs_dir, ".hidden.md"), "w", encoding="utf-8") as f:
            f.write("hidden file")

        result = scan_stale_stubs(vault_dir, "test-project")

        # Only .md files that pass os.listdir are scanned; .hidden.md starts with
        # a dot but still ends with .md, so it would be included. Let's just check
        # that the .txt file was excluded.
        names = {s.stub_name for s in result.stubs}
        assert "notes.txt" not in names
        assert "spec-valid.md" in names

    def test_last_synced_included_in_results(self, tmp_path):
        """The last_synced field is correctly extracted into StaleStubInfo."""
        vault_dir = str(tmp_path / "vault" / "projects")
        refs_dir = os.path.join(vault_dir, "test-project", "references")
        os.makedirs(refs_dir, exist_ok=True)

        with open(os.path.join(refs_dir, "spec-dated.md"), "w", encoding="utf-8") as f:
            f.write(
                "---\nsource: /path\nsource_hash: hash123\n"
                "last_synced: 2026-04-09\n---\n\n"
                "## Summary\n\nContent.\n"
            )

        result = scan_stale_stubs(vault_dir, "test-project")
        assert result.stubs[0].last_synced == "2026-04-09"

    def test_scan_result_dataclass_defaults(self):
        """StaleScanResult initializes with sensible defaults."""
        result = StaleScanResult(project_id="p")
        assert result.project_id == "p"
        assert result.stubs == []
        assert result.total == 0
        assert result.stale == 0
        assert result.missing_source == 0
        assert result.unenriched == 0
        assert result.orphaned == 0
        assert result.current == 0

    def test_stale_stub_info_defaults(self):
        """StaleStubInfo frozen dataclass has sensible defaults."""
        info = StaleStubInfo(stub_name="test.md", stub_path="/path/test.md")
        assert info.status == "current"
        assert info.source_path == ""
        assert info.recorded_hash == ""
        assert info.current_hash == ""
        assert info.last_synced == ""
        assert info.is_enriched is False
