"""Tests for src/reference_stub_enricher — LLM-based vault stub enrichment."""

from __future__ import annotations

import os
from dataclasses import dataclass
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from src.reference_stub_enricher import (
    SUMMARIZE_SYSTEM_PROMPT,
    ReferenceStubEnricher,
    parse_enrichment_response,
    update_stub_content,
)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@dataclass
class FakeChatResponse:
    """Minimal ChatResponse stand-in for testing."""

    content: list

    @property
    def text_parts(self) -> list[str]:
        return [block.text for block in self.content if hasattr(block, "text")]


@dataclass
class FakeTextBlock:
    text: str


@pytest.fixture
def fake_bus():
    bus = MagicMock()
    bus.emit = AsyncMock()
    bus.subscribe = MagicMock(return_value=MagicMock())
    return bus


@pytest.fixture
def fake_config():
    """Minimal MemoryConfig-like object with stub_enrichment fields."""

    @dataclass
    class FakeMemoryConfig:
        stub_enrichment_enabled: bool = True
        stub_enrichment_provider: str = ""
        stub_enrichment_model: str = ""
        stub_enrichment_max_source_chars: int = 20_000
        revision_provider: str = ""
        revision_model: str = ""

    return FakeMemoryConfig()


@pytest.fixture
def fake_provider():
    """Mock ChatProvider that returns a well-structured LLM response."""
    provider = AsyncMock()
    provider.create_message = AsyncMock(
        return_value=FakeChatResponse(
            content=[
                FakeTextBlock(
                    text=(
                        "## Summary\n"
                        "This document defines the main orchestration loop "
                        "including task assignment and agent lifecycle.\n\n"
                        "## Key Decisions\n"
                        "- Tick-based loop at ~5s interval\n"
                        "- Single agent per task\n"
                        "- Tasks assigned by priority then age\n\n"
                        "## Key Interfaces\n"
                        "- `Orchestrator.tick()` -- main loop entry\n"
                        "- `Orchestrator.assign_task()` -- agent selection\n"
                        "- EventBus integration for state changes"
                    )
                )
            ]
        )
    )
    return provider


@pytest.fixture
def vault_dir(tmp_path):
    """Create a vault/projects directory structure."""
    vault_projects = tmp_path / "vault" / "projects"
    vault_projects.mkdir(parents=True)
    return str(vault_projects)


@pytest.fixture
def enricher(fake_bus, vault_dir, fake_config, fake_provider):
    """Create a ReferenceStubEnricher with a mock provider."""
    return ReferenceStubEnricher(
        bus=fake_bus,
        vault_projects_dir=vault_dir,
        config=fake_config,
        provider=fake_provider,
        enabled=True,
    )


def _create_stub_file(vault_dir: str, project_id: str, stub_name: str) -> str:
    """Create a stub file with placeholder sections.

    Returns the path to the created stub file.
    """
    refs_dir = os.path.join(vault_dir, project_id, "references")
    os.makedirs(refs_dir, exist_ok=True)
    stub_path = os.path.join(refs_dir, stub_name)

    content = f"""\
---
tags: [spec, reference, auto-generated]
source: /workspace/specs/orchestrator.md
source_hash: abc123def456
last_synced: 2026-04-07
---

# Spec: Orchestrator

Full spec at `specs/orchestrator.md` in the {project_id} workspace.

## Excerpt

First few lines of the spec...

## Summary

*Summary pending -- will be generated by LLM enrichment.*

## Key Decisions

*Pending LLM extraction.*

## Key Interfaces

*Pending LLM extraction.*
"""
    with open(stub_path, "w", encoding="utf-8") as f:
        f.write(content)
    return stub_path


def _create_source_file(tmp_path, content: str = "") -> str:
    """Create a source spec file and return its path."""
    source = tmp_path / "workspace" / "specs" / "orchestrator.md"
    source.parent.mkdir(parents=True, exist_ok=True)
    if not content:
        content = """\
# Orchestrator Spec

## Overview
The orchestrator manages the main loop for task assignment.

## Design Decisions
- Tick-based loop at ~5s interval
- Single agent per task, no sharing
- Tasks assigned by priority then age

## Interfaces
- `Orchestrator.tick()` -- main loop entry
- `Orchestrator.assign_task()` -- agent selection
"""
    source.write_text(content, encoding="utf-8")
    return str(source)


# ---------------------------------------------------------------------------
# parse_enrichment_response tests
# ---------------------------------------------------------------------------


class TestParseEnrichmentResponse:
    """Tests for the parse_enrichment_response() function."""

    def test_parses_well_formed_response(self):
        response = (
            "## Summary\n"
            "This is the summary.\n\n"
            "## Key Decisions\n"
            "- Decision one\n"
            "- Decision two\n\n"
            "## Key Interfaces\n"
            "- `foo()` -- does things\n"
            "- `bar()` -- does other things"
        )
        result = parse_enrichment_response(response)
        assert "summary" in result["summary"].lower() or "This is the summary" in result["summary"]
        assert "Decision one" in result["key_decisions"]
        assert "`foo()`" in result["key_interfaces"]

    def test_empty_response_returns_empty_sections(self):
        result = parse_enrichment_response("")
        assert result["summary"] == ""
        assert result["key_decisions"] == ""
        assert result["key_interfaces"] == ""

    def test_partial_response_fills_available_sections(self):
        response = "## Summary\nJust a summary, no other sections."
        result = parse_enrichment_response(response)
        assert "Just a summary" in result["summary"]
        assert result["key_decisions"] == ""
        assert result["key_interfaces"] == ""

    def test_case_insensitive_headers(self):
        response = (
            "## summary\n"
            "Lower case summary.\n\n"
            "## KEY DECISIONS\n"
            "- Upper case decision\n\n"
            "## Key Interfaces\n"
            "- Mixed case interface"
        )
        result = parse_enrichment_response(response)
        assert "Lower case summary" in result["summary"]
        assert "Upper case decision" in result["key_decisions"]
        assert "Mixed case interface" in result["key_interfaces"]

    def test_extra_headers_ignored(self):
        response = (
            "## Summary\n"
            "The summary.\n\n"
            "## Additional Notes\n"
            "These are extra notes.\n\n"
            "## Key Decisions\n"
            "- A decision\n\n"
            "## Key Interfaces\n"
            "- An interface"
        )
        result = parse_enrichment_response(response)
        assert "The summary" in result["summary"]
        assert "A decision" in result["key_decisions"]
        assert "An interface" in result["key_interfaces"]

    def test_multiline_content_preserved(self):
        response = (
            "## Summary\n"
            "Line one of summary.\n"
            "Line two of summary.\n"
            "Line three.\n\n"
            "## Key Decisions\n"
            "- Decision A\n"
            "- Decision B\n"
            "- Decision C\n\n"
            "## Key Interfaces\n"
            "- Interface X"
        )
        result = parse_enrichment_response(response)
        assert "Line one" in result["summary"]
        assert "Line three" in result["summary"]
        assert "Decision A" in result["key_decisions"]
        assert "Decision C" in result["key_decisions"]


# ---------------------------------------------------------------------------
# update_stub_content tests
# ---------------------------------------------------------------------------


class TestUpdateStubContent:
    """Tests for the update_stub_content() function."""

    def test_replaces_placeholder_summary(self):
        existing = (
            "# Spec: Foo\n\n"
            "## Excerpt\n\nSome excerpt.\n\n"
            "## Summary\n\n"
            "*Summary pending -- will be generated by LLM enrichment.*\n\n"
            "## Key Decisions\n\n"
            "*Pending LLM extraction.*\n\n"
            "## Key Interfaces\n\n"
            "*Pending LLM extraction.*\n"
        )
        sections = {
            "summary": "This is the real summary.",
            "key_decisions": "- Real decision",
            "key_interfaces": "- `real_fn()` -- does stuff",
        }
        result = update_stub_content(existing, sections)
        assert "This is the real summary." in result
        assert "- Real decision" in result
        assert "`real_fn()`" in result
        assert "*Summary pending" not in result
        assert "*Pending LLM extraction.*" not in result

    def test_preserves_frontmatter(self):
        existing = (
            "---\ntags: [spec]\nsource: /foo\n---\n\n"
            "# Spec: Bar\n\n"
            "## Excerpt\n\nExcerpt text.\n\n"
            "## Summary\n\n*Placeholder*\n\n"
            "## Key Decisions\n\n*Placeholder*\n\n"
            "## Key Interfaces\n\n*Placeholder*\n"
        )
        sections = {"summary": "New summary.", "key_decisions": "", "key_interfaces": ""}
        result = update_stub_content(existing, sections)
        assert "---\ntags: [spec]\nsource: /foo\n---" in result
        assert "New summary." in result
        # Empty sections should NOT replace existing content
        assert "*Placeholder*" in result

    def test_empty_sections_preserve_existing(self):
        existing = (
            "## Summary\n\nExisting summary.\n\n"
            "## Key Decisions\n\n- Existing decision\n\n"
            "## Key Interfaces\n\n- Existing interface\n"
        )
        sections = {"summary": "", "key_decisions": "", "key_interfaces": ""}
        result = update_stub_content(existing, sections)
        assert result == existing

    def test_preserves_excerpt_section(self):
        existing = (
            "## Excerpt\n\nFirst lines of the file...\n\n"
            "## Summary\n\n*Placeholder*\n\n"
            "## Key Decisions\n\n*Placeholder*\n\n"
            "## Key Interfaces\n\n*Placeholder*\n"
        )
        sections = {
            "summary": "New summary.",
            "key_decisions": "- New decision",
            "key_interfaces": "- New interface",
        }
        result = update_stub_content(existing, sections)
        assert "First lines of the file..." in result
        assert "New summary." in result


# ---------------------------------------------------------------------------
# ReferenceStubEnricher tests
# ---------------------------------------------------------------------------


class TestReferenceStubEnricherSubscribe:
    """Tests for subscription lifecycle."""

    def test_subscribe_calls_bus_subscribe(self, enricher, fake_bus):
        enricher.subscribe()
        fake_bus.subscribe.assert_called_once_with(
            "workspace.spec.changed",
            enricher._on_spec_changed,
        )

    def test_double_subscribe_is_idempotent(self, enricher, fake_bus):
        enricher.subscribe()
        enricher.subscribe()
        fake_bus.subscribe.assert_called_once()

    def test_unsubscribe_calls_unsubscribe_handle(self, enricher, fake_bus):
        enricher.subscribe()
        unsub = fake_bus.subscribe.return_value
        enricher.unsubscribe()
        unsub.assert_called_once()


class TestReferenceStubEnricherProperties:
    """Tests for enricher properties."""

    def test_enabled_default_true(self, enricher):
        assert enricher.enabled is True

    def test_enabled_setter(self, enricher):
        enricher.enabled = False
        assert enricher.enabled is False

    def test_initial_counters_zero(self, enricher):
        assert enricher.total_enriched == 0
        assert enricher.total_failed == 0


class TestReferenceStubEnricherEnrich:
    """Tests for the enrich_stub() method."""

    @pytest.mark.asyncio
    async def test_successful_enrichment(self, enricher, vault_dir, tmp_path):
        project_id = "test-project"
        stub_name = "spec-orchestrator.md"

        # Create source and stub files
        source_path = _create_source_file(tmp_path)
        _create_stub_file(vault_dir, project_id, stub_name)

        result = await enricher.enrich_stub(
            project_id=project_id,
            abs_path=source_path,
            stub_name=stub_name,
        )

        assert result.success is True
        assert result.project_id == project_id
        assert result.stub_name == stub_name
        assert result.summary != ""
        assert result.error == ""
        assert enricher.total_enriched == 1
        assert enricher.total_failed == 0

    @pytest.mark.asyncio
    async def test_enrichment_updates_stub_file(self, enricher, vault_dir, tmp_path):
        project_id = "test-project"
        stub_name = "spec-orchestrator.md"

        source_path = _create_source_file(tmp_path)
        stub_path = _create_stub_file(vault_dir, project_id, stub_name)

        await enricher.enrich_stub(
            project_id=project_id,
            abs_path=source_path,
            stub_name=stub_name,
        )

        # Verify stub file was updated
        with open(stub_path, encoding="utf-8") as f:
            content = f.read()

        assert "*Summary pending" not in content
        assert "orchestration loop" in content.lower() or "task assignment" in content.lower()
        assert "Tick-based loop" in content or "priority" in content.lower()

    @pytest.mark.asyncio
    async def test_missing_source_file_fails(self, enricher, vault_dir):
        project_id = "test-project"
        stub_name = "spec-missing.md"
        _create_stub_file(vault_dir, project_id, stub_name)

        result = await enricher.enrich_stub(
            project_id=project_id,
            abs_path="/nonexistent/file.md",
            stub_name=stub_name,
        )

        assert result.success is False
        assert "Could not read" in result.error
        assert enricher.total_failed == 1

    @pytest.mark.asyncio
    async def test_missing_stub_file_fails(self, enricher, tmp_path):
        project_id = "test-project"
        stub_name = "spec-no-stub.md"
        source_path = _create_source_file(tmp_path)

        result = await enricher.enrich_stub(
            project_id=project_id,
            abs_path=source_path,
            stub_name=stub_name,
        )

        assert result.success is False
        assert "Stub file not found" in result.error

    @pytest.mark.asyncio
    async def test_no_provider_fails(self, fake_bus, vault_dir, fake_config, tmp_path):
        enricher = ReferenceStubEnricher(
            bus=fake_bus,
            vault_projects_dir=vault_dir,
            config=fake_config,
            provider=None,  # No provider
            enabled=True,
        )
        # Patch _get_provider to return None (simulates missing credentials)
        enricher._get_provider = MagicMock(return_value=None)

        project_id = "test-project"
        stub_name = "spec-test.md"
        source_path = _create_source_file(tmp_path)
        _create_stub_file(vault_dir, project_id, stub_name)

        result = await enricher.enrich_stub(
            project_id=project_id,
            abs_path=source_path,
            stub_name=stub_name,
        )

        assert result.success is False
        assert "No LLM provider" in result.error

    @pytest.mark.asyncio
    async def test_llm_exception_fails_gracefully(
        self, fake_bus, vault_dir, fake_config, tmp_path
    ):
        provider = AsyncMock()
        provider.create_message = AsyncMock(side_effect=RuntimeError("API timeout"))

        enricher = ReferenceStubEnricher(
            bus=fake_bus,
            vault_projects_dir=vault_dir,
            config=fake_config,
            provider=provider,
            enabled=True,
        )

        project_id = "test-project"
        stub_name = "spec-test.md"
        source_path = _create_source_file(tmp_path)
        _create_stub_file(vault_dir, project_id, stub_name)

        result = await enricher.enrich_stub(
            project_id=project_id,
            abs_path=source_path,
            stub_name=stub_name,
        )

        assert result.success is False
        assert "LLM summarization failed" in result.error

    @pytest.mark.asyncio
    async def test_empty_llm_response_fails(self, fake_bus, vault_dir, fake_config, tmp_path):
        provider = AsyncMock()
        provider.create_message = AsyncMock(
            return_value=FakeChatResponse(content=[FakeTextBlock(text="")])
        )

        enricher = ReferenceStubEnricher(
            bus=fake_bus,
            vault_projects_dir=vault_dir,
            config=fake_config,
            provider=provider,
            enabled=True,
        )

        project_id = "test-project"
        stub_name = "spec-test.md"
        source_path = _create_source_file(tmp_path)
        _create_stub_file(vault_dir, project_id, stub_name)

        result = await enricher.enrich_stub(
            project_id=project_id,
            abs_path=source_path,
            stub_name=stub_name,
        )

        assert result.success is False
        assert "empty sections" in result.error


class TestReferenceStubEnricherEventHandler:
    """Tests for the _on_spec_changed event handler."""

    @pytest.mark.asyncio
    async def test_created_event_triggers_enrichment(self, enricher, vault_dir, tmp_path):
        project_id = "test-project"
        stub_name = "spec-orchestrator.md"
        source_path = _create_source_file(tmp_path)
        _create_stub_file(vault_dir, project_id, stub_name)

        event_data = {
            "_event_type": "workspace.spec.changed",
            "project_id": project_id,
            "workspace_path": str(tmp_path / "workspace"),
            "rel_path": "specs/orchestrator.md",
            "abs_path": source_path,
            "operation": "created",
            "content_hash": "abc123def456",
            "stub_name": stub_name,
        }

        await enricher._on_spec_changed(event_data)

        assert enricher.total_enriched == 1

    @pytest.mark.asyncio
    async def test_modified_event_triggers_enrichment(self, enricher, vault_dir, tmp_path):
        project_id = "test-project"
        stub_name = "spec-orchestrator.md"
        source_path = _create_source_file(tmp_path)
        _create_stub_file(vault_dir, project_id, stub_name)

        event_data = {
            "_event_type": "workspace.spec.changed",
            "project_id": project_id,
            "workspace_path": str(tmp_path / "workspace"),
            "rel_path": "specs/orchestrator.md",
            "abs_path": source_path,
            "operation": "modified",
            "content_hash": "abc123def456",
            "stub_name": stub_name,
        }

        await enricher._on_spec_changed(event_data)

        assert enricher.total_enriched == 1

    @pytest.mark.asyncio
    async def test_deleted_event_is_ignored(self, enricher):
        event_data = {
            "_event_type": "workspace.spec.changed",
            "project_id": "test-project",
            "workspace_path": "/workspace",
            "rel_path": "specs/orchestrator.md",
            "abs_path": "/workspace/specs/orchestrator.md",
            "operation": "deleted",
            "content_hash": "",
            "stub_name": "spec-orchestrator.md",
        }

        await enricher._on_spec_changed(event_data)

        assert enricher.total_enriched == 0
        assert enricher.total_failed == 0

    @pytest.mark.asyncio
    async def test_disabled_enricher_ignores_events(self, enricher, vault_dir, tmp_path):
        enricher.enabled = False

        event_data = {
            "_event_type": "workspace.spec.changed",
            "project_id": "test-project",
            "abs_path": _create_source_file(tmp_path),
            "operation": "created",
            "stub_name": "spec-test.md",
        }

        await enricher._on_spec_changed(event_data)

        assert enricher.total_enriched == 0

    @pytest.mark.asyncio
    async def test_incomplete_event_data_logged(self, enricher):
        """Events with missing required fields should be skipped gracefully."""
        event_data = {
            "_event_type": "workspace.spec.changed",
            "project_id": "test-project",
            # Missing abs_path and stub_name
            "operation": "created",
        }

        await enricher._on_spec_changed(event_data)

        assert enricher.total_enriched == 0
        assert enricher.total_failed == 0


class TestReferenceStubEnricherReadSource:
    """Tests for source file reading and truncation."""

    def test_reads_normal_file(self, enricher, tmp_path):
        source = tmp_path / "test.md"
        source.write_text("# Hello\nWorld", encoding="utf-8")
        content = enricher._read_source(str(source))
        assert content == "# Hello\nWorld"

    def test_truncates_large_file(self, tmp_path, fake_bus, fake_config, fake_provider):
        vault_dir = str(tmp_path / "vault")
        enricher = ReferenceStubEnricher(
            bus=fake_bus,
            vault_projects_dir=vault_dir,
            config=fake_config,
            provider=fake_provider,
            max_source_chars=100,
        )

        source = tmp_path / "large.md"
        source.write_text("x" * 500, encoding="utf-8")
        content = enricher._read_source(str(source))

        assert len(content) > 100  # includes truncation note
        assert "[Document truncated at 100 characters" in content

    def test_missing_file_returns_empty(self, enricher):
        content = enricher._read_source("/nonexistent/file.md")
        assert content == ""

    def test_empty_file_returns_empty(self, enricher, tmp_path):
        source = tmp_path / "empty.md"
        source.write_text("", encoding="utf-8")
        content = enricher._read_source(str(source))
        assert content == ""

    def test_whitespace_only_file_returns_empty(self, enricher, tmp_path):
        source = tmp_path / "whitespace.md"
        source.write_text("   \n\n  \t  ", encoding="utf-8")
        content = enricher._read_source(str(source))
        assert content == ""


class TestReferenceStubEnricherSummarize:
    """Tests for the _summarize_document method."""

    @pytest.mark.asyncio
    async def test_sends_correct_prompt_to_llm(self, enricher, fake_provider):
        content = "# Test Doc\nSome content here."
        await enricher._summarize_document(fake_provider, content)

        fake_provider.create_message.assert_called_once()
        call_kwargs = fake_provider.create_message.call_args.kwargs
        assert call_kwargs["system"] == SUMMARIZE_SYSTEM_PROMPT
        assert call_kwargs["max_tokens"] == 1024
        messages = call_kwargs["messages"]
        assert len(messages) == 1
        assert messages[0]["role"] == "user"
        assert "# Test Doc" in messages[0]["content"]
        assert "Some content here." in messages[0]["content"]

    @pytest.mark.asyncio
    async def test_empty_text_parts_returns_empty_sections(self, enricher):
        provider = AsyncMock()
        provider.create_message = AsyncMock(
            return_value=FakeChatResponse(content=[])
        )
        result = await enricher._summarize_document(provider, "some content")
        assert result["summary"] == ""
        assert result["key_decisions"] == ""
        assert result["key_interfaces"] == ""


class TestReferenceStubEnricherProviderFallback:
    """Tests for LLM provider fallback chain."""

    def test_uses_injected_provider(self, enricher, fake_provider):
        result = enricher._get_provider()
        assert result is fake_provider

    def test_creates_provider_from_config(self, fake_bus, fake_config, tmp_path):
        enricher = ReferenceStubEnricher(
            bus=fake_bus,
            vault_projects_dir=str(tmp_path),
            config=fake_config,
            provider=None,
            enabled=True,
        )

        mock_provider = MagicMock()
        with patch(
            "src.chat_providers.create_chat_provider",
            return_value=mock_provider,
        ) as mock_create:
            result = enricher._get_provider()
            assert result is mock_provider
            mock_create.assert_called_once()

    def test_fallback_to_revision_provider(self, fake_bus, tmp_path):
        @dataclass
        class Config:
            stub_enrichment_enabled: bool = True
            stub_enrichment_provider: str = ""
            stub_enrichment_model: str = ""
            stub_enrichment_max_source_chars: int = 20_000
            revision_provider: str = "ollama"
            revision_model: str = "qwen:7b"

        enricher = ReferenceStubEnricher(
            bus=fake_bus,
            vault_projects_dir=str(tmp_path),
            config=Config(),
            provider=None,
            enabled=True,
        )

        with patch("src.chat_providers.create_chat_provider") as mock_create:
            mock_create.return_value = MagicMock()
            enricher._get_provider()
            call_args = mock_create.call_args[0][0]
            assert call_args.provider == "ollama"
            assert call_args.model == "qwen:7b"

    def test_stub_enrichment_provider_takes_precedence(self, fake_bus, tmp_path):
        @dataclass
        class Config:
            stub_enrichment_enabled: bool = True
            stub_enrichment_provider: str = "gemini"
            stub_enrichment_model: str = "gemini-2.5-flash"
            stub_enrichment_max_source_chars: int = 20_000
            revision_provider: str = "ollama"
            revision_model: str = "qwen:7b"

        enricher = ReferenceStubEnricher(
            bus=fake_bus,
            vault_projects_dir=str(tmp_path),
            config=Config(),
            provider=None,
            enabled=True,
        )

        with patch("src.chat_providers.create_chat_provider") as mock_create:
            mock_create.return_value = MagicMock()
            enricher._get_provider()
            call_args = mock_create.call_args[0][0]
            assert call_args.provider == "gemini"
            assert call_args.model == "gemini-2.5-flash"


class TestReferenceStubEnricherLargeFiles:
    """Tests for handling large spec files (>5000 tokens, per roadmap 6.3.5f)."""

    @pytest.mark.asyncio
    async def test_large_file_truncated_but_enriched(self, vault_dir, fake_bus, fake_config, tmp_path):
        """Stub generation handles large spec files by truncating and summarizing."""
        # Set a small limit for testing
        fake_config.stub_enrichment_max_source_chars = 500

        provider = AsyncMock()
        provider.create_message = AsyncMock(
            return_value=FakeChatResponse(
                content=[
                    FakeTextBlock(
                        text=(
                            "## Summary\n"
                            "A very large specification document.\n\n"
                            "## Key Decisions\n"
                            "- Large-scale architecture\n\n"
                            "## Key Interfaces\n"
                            "- Main API surface"
                        )
                    )
                ]
            )
        )

        enricher = ReferenceStubEnricher(
            bus=fake_bus,
            vault_projects_dir=vault_dir,
            config=fake_config,
            provider=provider,
            enabled=True,
            max_source_chars=500,
        )

        # Create a large source file
        source = tmp_path / "workspace" / "specs" / "big-spec.md"
        source.parent.mkdir(parents=True, exist_ok=True)
        source.write_text("# Big Spec\n" + "Content line.\n" * 1000, encoding="utf-8")

        project_id = "test-project"
        stub_name = "spec-big-spec.md"
        _create_stub_file(vault_dir, project_id, stub_name)

        result = await enricher.enrich_stub(
            project_id=project_id,
            abs_path=str(source),
            stub_name=stub_name,
        )

        assert result.success is True
        # Verify the LLM received truncated content
        call_kwargs = provider.create_message.call_args.kwargs
        user_msg = call_kwargs["messages"][0]["content"]
        assert "[Document truncated at 500 characters" in user_msg


class TestReferenceStubEnricherMultipleFiles:
    """Tests for handling multiple files."""

    @pytest.mark.asyncio
    async def test_multiple_enrichments_increment_counter(
        self, enricher, vault_dir, tmp_path
    ):
        """Multiple spec files changed simultaneously each get enriched."""
        for name in ["orchestrator", "database", "supervisor"]:
            source = tmp_path / "workspace" / "specs" / f"{name}.md"
            source.parent.mkdir(parents=True, exist_ok=True)
            source.write_text(f"# {name.title()} Spec\nContent about {name}.", encoding="utf-8")

            stub_name = f"spec-{name}.md"
            _create_stub_file(vault_dir, "test-project", stub_name)

            result = await enricher.enrich_stub(
                project_id="test-project",
                abs_path=str(source),
                stub_name=stub_name,
            )
            assert result.success is True

        assert enricher.total_enriched == 3
        assert enricher.total_failed == 0


class TestReferenceStubEnricherStubFormat:
    """Tests verifying enriched stubs maintain Obsidian-compatible format."""

    @pytest.mark.asyncio
    async def test_enriched_stub_retains_frontmatter(self, enricher, vault_dir, tmp_path):
        project_id = "test-project"
        stub_name = "spec-orchestrator.md"
        source_path = _create_source_file(tmp_path)
        stub_path = _create_stub_file(vault_dir, project_id, stub_name)

        await enricher.enrich_stub(
            project_id=project_id,
            abs_path=source_path,
            stub_name=stub_name,
        )

        with open(stub_path, encoding="utf-8") as f:
            content = f.read()

        # Frontmatter must be preserved
        assert content.startswith("---\n")
        assert "tags: [spec, reference, auto-generated]" in content
        assert "source:" in content
        assert "source_hash:" in content
        assert "last_synced:" in content

    @pytest.mark.asyncio
    async def test_enriched_stub_retains_excerpt(self, enricher, vault_dir, tmp_path):
        project_id = "test-project"
        stub_name = "spec-orchestrator.md"
        source_path = _create_source_file(tmp_path)
        stub_path = _create_stub_file(vault_dir, project_id, stub_name)

        await enricher.enrich_stub(
            project_id=project_id,
            abs_path=source_path,
            stub_name=stub_name,
        )

        with open(stub_path, encoding="utf-8") as f:
            content = f.read()

        # Excerpt section must be preserved
        assert "## Excerpt" in content

    @pytest.mark.asyncio
    async def test_enriched_stub_has_all_sections(self, enricher, vault_dir, tmp_path):
        project_id = "test-project"
        stub_name = "spec-orchestrator.md"
        source_path = _create_source_file(tmp_path)
        stub_path = _create_stub_file(vault_dir, project_id, stub_name)

        await enricher.enrich_stub(
            project_id=project_id,
            abs_path=source_path,
            stub_name=stub_name,
        )

        with open(stub_path, encoding="utf-8") as f:
            content = f.read()

        # All expected sections must be present
        assert "## Excerpt" in content
        assert "## Summary" in content
        assert "## Key Decisions" in content
        assert "## Key Interfaces" in content
