"""baseline schema

Revision ID: 311e98c39ffa
Revises:
Create Date: 2026-04-03 14:07:24.029284

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "311e98c39ffa"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_profiles",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("model", sa.Text(), server_default="", nullable=False),
        sa.Column("permission_mode", sa.Text(), server_default="", nullable=False),
        sa.Column("allowed_tools", sa.Text(), server_default="[]", nullable=False),
        sa.Column("mcp_servers", sa.Text(), server_default="{}", nullable=False),
        sa.Column("system_prompt_suffix", sa.Text(), server_default="", nullable=False),
        sa.Column("install", sa.Text(), server_default="{}", nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "agents",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("agent_type", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), server_default="IDLE", nullable=False),
        sa.Column("current_task_id", sa.Text(), nullable=True),
        sa.Column("checkout_path", sa.Text(), nullable=True),
        sa.Column("repo_id", sa.Text(), nullable=True),
        sa.Column("pid", sa.Integer(), nullable=True),
        sa.Column("last_heartbeat", sa.Float(), nullable=True),
        sa.Column("total_tokens_used", sa.Integer(), server_default="0", nullable=False),
        sa.Column("session_tokens_used", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["current_task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repo_id"],
            ["repos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "archived_tasks",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("project_id", sa.Text(), nullable=False),
        sa.Column("parent_task_id", sa.Text(), nullable=True),
        sa.Column("repo_id", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("priority", sa.Integer(), server_default="100", nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("verification_type", sa.Text(), server_default="auto_test", nullable=False),
        sa.Column("retry_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_retries", sa.Integer(), server_default="3", nullable=False),
        sa.Column("assigned_agent_id", sa.Text(), nullable=True),
        sa.Column("branch_name", sa.Text(), nullable=True),
        sa.Column("resume_after", sa.Float(), nullable=True),
        sa.Column("requires_approval", sa.Integer(), server_default="0", nullable=False),
        sa.Column("pr_url", sa.Text(), nullable=True),
        sa.Column("plan_source", sa.Text(), nullable=True),
        sa.Column("is_plan_subtask", sa.Integer(), server_default="0", nullable=False),
        sa.Column("task_type", sa.Text(), nullable=True),
        sa.Column("profile_id", sa.Text(), nullable=True),
        sa.Column("preferred_workspace_id", sa.Text(), nullable=True),
        sa.Column("attachments", sa.Text(), server_default="[]", nullable=True),
        sa.Column("auto_approve_plan", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.Column("archived_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chat_analyzer_suggestions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Text(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("suggestion_type", sa.Text(), nullable=False),
        sa.Column("suggestion_text", sa.Text(), nullable=False),
        sa.Column("suggestion_hash", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("resolved_at", sa.Float(), nullable=True),
        sa.Column("context_snapshot", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("chat_analyzer_suggestions", schema=None) as batch_op:
        batch_op.create_index("idx_chat_analyzer_hash", ["suggestion_hash"], unique=False)
        batch_op.create_index("idx_chat_analyzer_project", ["project_id", "status"], unique=False)

    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("project_id", sa.Text(), nullable=True),
        sa.Column("task_id", sa.Text(), nullable=True),
        sa.Column("agent_id", sa.Text(), nullable=True),
        sa.Column("payload", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "plugins",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("version", sa.Text(), server_default="0.0.0", nullable=False),
        sa.Column("source_url", sa.Text(), server_default="", nullable=False),
        sa.Column("source_rev", sa.Text(), server_default="", nullable=False),
        sa.Column("source_branch", sa.Text(), server_default="", nullable=False),
        sa.Column("install_path", sa.Text(), server_default="", nullable=False),
        sa.Column("status", sa.Text(), server_default="installed", nullable=False),
        sa.Column("config", sa.Text(), server_default="{}", nullable=False),
        sa.Column("permissions", sa.Text(), server_default="[]", nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("installed_at", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rate_limits",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("agent_type", sa.Text(), nullable=False),
        sa.Column("limit_type", sa.Text(), nullable=False),
        sa.Column("max_tokens", sa.Integer(), nullable=False),
        sa.Column("current_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("window_start", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "system_config",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("project_id", sa.Text(), nullable=False),
        sa.Column("parent_task_id", sa.Text(), nullable=True),
        sa.Column("repo_id", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("priority", sa.Integer(), server_default="100", nullable=False),
        sa.Column("status", sa.Text(), server_default="DEFINED", nullable=False),
        sa.Column("verification_type", sa.Text(), server_default="auto_test", nullable=False),
        sa.Column("retry_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_retries", sa.Integer(), server_default="3", nullable=False),
        sa.Column("assigned_agent_id", sa.Text(), nullable=True),
        sa.Column("branch_name", sa.Text(), nullable=True),
        sa.Column("resume_after", sa.Float(), nullable=True),
        sa.Column("requires_approval", sa.Integer(), server_default="0", nullable=False),
        sa.Column("pr_url", sa.Text(), nullable=True),
        sa.Column("plan_source", sa.Text(), nullable=True),
        sa.Column("is_plan_subtask", sa.Integer(), server_default="0", nullable=False),
        sa.Column("task_type", sa.Text(), nullable=True),
        sa.Column("profile_id", sa.Text(), nullable=True),
        sa.Column("preferred_workspace_id", sa.Text(), nullable=True),
        sa.Column("attachments", sa.Text(), server_default="[]", nullable=True),
        sa.Column("auto_approve_plan", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["preferred_workspace_id"],
            ["workspaces.id"],
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["agent_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repo_id"],
            ["repos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workspaces",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("project_id", sa.Text(), nullable=False),
        sa.Column("workspace_path", sa.Text(), nullable=False),
        sa.Column("source_type", sa.Text(), server_default="clone", nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("locked_by_agent_id", sa.Text(), nullable=True),
        sa.Column("locked_by_task_id", sa.Text(), nullable=True),
        sa.Column("locked_at", sa.Float(), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["locked_by_agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["locked_by_task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "workspace_path"),
    )
    op.create_table(
        "plugin_data",
        sa.Column("plugin_id", sa.Text(), nullable=False),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value", sa.Text(), server_default="{}", nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plugin_id"],
            ["plugins.id"],
        ),
        sa.PrimaryKeyConstraint("plugin_id", "key"),
    )
    with op.batch_alter_table("plugin_data", schema=None) as batch_op:
        batch_op.create_index("idx_plugin_data_plugin_id", ["plugin_id"], unique=False)

    op.create_table(
        "projects",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("credit_weight", sa.Float(), server_default="1.0", nullable=False),
        sa.Column("max_concurrent_agents", sa.Integer(), server_default="2", nullable=False),
        sa.Column("status", sa.Text(), server_default="ACTIVE", nullable=False),
        sa.Column("total_tokens_used", sa.Integer(), server_default="0", nullable=False),
        sa.Column("budget_limit", sa.Integer(), nullable=True),
        sa.Column("workspace_path", sa.Text(), nullable=True),
        sa.Column("discord_channel_id", sa.Text(), nullable=True),
        sa.Column("discord_control_channel_id", sa.Text(), nullable=True),
        sa.Column("repo_url", sa.Text(), server_default="", nullable=True),
        sa.Column("repo_default_branch", sa.Text(), server_default="main", nullable=True),
        sa.Column("default_profile_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["default_profile_id"],
            ["agent_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_context",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("task_id", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_criteria",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("task_id", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_dependencies",
        sa.Column("task_id", sa.Text(), nullable=False),
        sa.Column("depends_on_task_id", sa.Text(), nullable=False),
        sa.CheckConstraint("task_id != depends_on_task_id"),
        sa.ForeignKeyConstraint(
            ["depends_on_task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("task_id", "depends_on_task_id"),
    )
    with op.batch_alter_table("task_dependencies", schema=None) as batch_op:
        batch_op.create_index("idx_task_deps_depends_on", ["depends_on_task_id"], unique=False)
        batch_op.create_index("idx_task_deps_task_id", ["task_id"], unique=False)

    op.create_table(
        "task_results",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("task_id", sa.Text(), nullable=False),
        sa.Column("agent_id", sa.Text(), nullable=False),
        sa.Column("result", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), server_default="", nullable=False),
        sa.Column("files_changed", sa.Text(), server_default="[]", nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("tokens_used", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_tools",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("task_id", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("config", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hooks",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("project_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Integer(), server_default="1", nullable=False),
        sa.Column("trigger", sa.Text(), nullable=False),
        sa.Column("context_steps", sa.Text(), server_default="[]", nullable=False),
        sa.Column("prompt_template", sa.Text(), nullable=False),
        sa.Column("llm_config", sa.Text(), nullable=True),
        sa.Column("cooldown_seconds", sa.Integer(), server_default="3600", nullable=False),
        sa.Column("max_tokens_per_run", sa.Integer(), nullable=True),
        sa.Column("last_triggered_at", sa.Float(), nullable=True),
        sa.Column("plugin_id", sa.Text(), nullable=True),
        sa.Column("source_hash", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("hooks", schema=None) as batch_op:
        batch_op.create_index("idx_hooks_plugin_id", ["plugin_id"], unique=False)

    op.create_table(
        "repos",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("project_id", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("default_branch", sa.Text(), server_default="main", nullable=False),
        sa.Column("checkout_base_path", sa.Text(), nullable=False),
        sa.Column("source_type", sa.Text(), server_default="clone", nullable=False),
        sa.Column("source_path", sa.Text(), server_default="", nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "token_ledger",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("project_id", sa.Text(), nullable=False),
        sa.Column("agent_id", sa.Text(), nullable=False),
        sa.Column("task_id", sa.Text(), nullable=False),
        sa.Column("tokens_used", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hook_runs",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("hook_id", sa.Text(), nullable=False),
        sa.Column("project_id", sa.Text(), nullable=False),
        sa.Column("trigger_reason", sa.Text(), nullable=False),
        sa.Column("event_data", sa.Text(), nullable=True),
        sa.Column("context_results", sa.Text(), nullable=True),
        sa.Column("prompt_sent", sa.Text(), nullable=True),
        sa.Column("llm_response", sa.Text(), nullable=True),
        sa.Column("actions_taken", sa.Text(), nullable=True),
        sa.Column("skipped_reason", sa.Text(), nullable=True),
        sa.Column("tokens_used", sa.Integer(), server_default="0", nullable=False),
        sa.Column("status", sa.Text(), server_default="running", nullable=False),
        sa.Column("started_at", sa.Float(), nullable=False),
        sa.Column("completed_at", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["hook_id"],
            ["hooks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hook_runs")
    op.drop_table("token_ledger")
    op.drop_table("repos")
    with op.batch_alter_table("hooks", schema=None) as batch_op:
        batch_op.drop_index("idx_hooks_plugin_id")

    op.drop_table("hooks")
    op.drop_table("task_tools")
    op.drop_table("task_results")
    with op.batch_alter_table("task_dependencies", schema=None) as batch_op:
        batch_op.drop_index("idx_task_deps_task_id")
        batch_op.drop_index("idx_task_deps_depends_on")

    op.drop_table("task_dependencies")
    op.drop_table("task_criteria")
    op.drop_table("task_context")
    op.drop_table("projects")
    with op.batch_alter_table("plugin_data", schema=None) as batch_op:
        batch_op.drop_index("idx_plugin_data_plugin_id")

    op.drop_table("plugin_data")
    op.drop_table("workspaces")
    op.drop_table("tasks")
    op.drop_table("system_config")
    op.drop_table("rate_limits")
    op.drop_table("plugins")
    op.drop_table("events")
    with op.batch_alter_table("chat_analyzer_suggestions", schema=None) as batch_op:
        batch_op.drop_index("idx_chat_analyzer_project")
        batch_op.drop_index("idx_chat_analyzer_hash")

    op.drop_table("chat_analyzer_suggestions")
    op.drop_table("archived_tasks")
    op.drop_table("agents")
    op.drop_table("agent_profiles")
    # ### end Alembic commands ###
