"""add default_agent_type to projects and per-project profile support

Revision ID: 3133bc141e0e
Revises: 8be724ef5414
Create Date: 2026-04-16 14:21:10.267476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3133bc141e0e'
down_revision: Union[str, Sequence[str], None] = '8be724ef5414'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_agent_type', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('default_agent_type')

    # ### end Alembic commands ###
