"""add agent_type affinity and workspace_mode columns to tasks

Revision ID: 4599a1026fdf
Revises: f6f7c1049974
Create Date: 2026-04-09 19:37:31.862921

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4599a1026fdf"
down_revision: Union[str, Sequence[str], None] = "f6f7c1049974"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("archived_tasks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("agent_type", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("affinity_agent_id", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("affinity_reason", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("workspace_mode", sa.Text(), nullable=True))

    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("agent_type", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("affinity_agent_id", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("affinity_reason", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("workspace_mode", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_column("workspace_mode")
        batch_op.drop_column("affinity_reason")
        batch_op.drop_column("affinity_agent_id")
        batch_op.drop_column("agent_type")

    with op.batch_alter_table("archived_tasks", schema=None) as batch_op:
        batch_op.drop_column("workspace_mode")
        batch_op.drop_column("affinity_reason")
        batch_op.drop_column("affinity_agent_id")
        batch_op.drop_column("agent_type")

    # ### end Alembic commands ###
