"""add workflows table for coordination playbooks

Revision ID: 6402d0c331c4
Revises: e43d09839087
Create Date: 2026-04-09 18:11:23.535133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6402d0c331c4'
down_revision: Union[str, Sequence[str], None] = 'e43d09839087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('workflow_id', sa.Text(), nullable=False),
    sa.Column('playbook_id', sa.Text(), nullable=False),
    sa.Column('playbook_run_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='running', nullable=False),
    sa.Column('current_stage', sa.Text(), nullable=True),
    sa.Column('task_ids', sa.Text(), server_default='[]', nullable=False),
    sa.Column('agent_affinity', sa.Text(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('completed_at', sa.Float(), nullable=True),
    sa.CheckConstraint("status IN ('running', 'paused', 'completed', 'failed')", name='ck_workflows_status'),
    sa.ForeignKeyConstraint(['playbook_run_id'], ['playbook_runs.run_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('workflow_id')
    )
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.create_index('idx_workflows_playbook_id', ['playbook_id'], unique=False)
        batch_op.create_index('idx_workflows_playbook_run_id', ['playbook_run_id'], unique=False)
        batch_op.create_index('idx_workflows_project_id', ['project_id'], unique=False)
        batch_op.create_index('idx_workflows_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_index('idx_workflows_status')
        batch_op.drop_index('idx_workflows_project_id')
        batch_op.drop_index('idx_workflows_playbook_run_id')
        batch_op.drop_index('idx_workflows_playbook_id')

    op.drop_table('workflows')
    # ### end Alembic commands ###
