"""add pinned_graph column to playbook_runs

Revision ID: 7a4c8681d23f
Revises: 8ff96bdb9ae6
Create Date: 2026-04-09 10:41:31.484613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a4c8681d23f'
down_revision: Union[str, Sequence[str], None] = '8ff96bdb9ae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playbook_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pinned_graph', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playbook_runs', schema=None) as batch_op:
        batch_op.drop_column('pinned_graph')

    # ### end Alembic commands ###
