"""add playbook_runs table

Revision ID: 8ff96bdb9ae6
Revises: d985baeab5c6
Create Date: 2026-04-09 09:26:42.430405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ff96bdb9ae6'
down_revision: Union[str, Sequence[str], None] = 'd985baeab5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playbook_runs',
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('playbook_id', sa.Text(), nullable=False),
    sa.Column('playbook_version', sa.Integer(), nullable=False),
    sa.Column('trigger_event', sa.Text(), server_default='{}', nullable=False),
    sa.Column('status', sa.Text(), server_default='running', nullable=False),
    sa.Column('current_node', sa.Text(), nullable=True),
    sa.Column('conversation_history', sa.Text(), server_default='[]', nullable=False),
    sa.Column('node_trace', sa.Text(), server_default='[]', nullable=False),
    sa.Column('tokens_used', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_at', sa.Float(), nullable=False),
    sa.Column('completed_at', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('running', 'paused', 'completed', 'failed', 'timed_out')", name='ck_playbook_runs_status'),
    sa.PrimaryKeyConstraint('run_id')
    )
    with op.batch_alter_table('playbook_runs', schema=None) as batch_op:
        batch_op.create_index('idx_playbook_runs_playbook_id', ['playbook_id'], unique=False)
        batch_op.create_index('idx_playbook_runs_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playbook_runs', schema=None) as batch_op:
        batch_op.drop_index('idx_playbook_runs_status')
        batch_op.drop_index('idx_playbook_runs_playbook_id')

    op.drop_table('playbook_runs')
    # ### end Alembic commands ###
