"""add skip_verification column to tasks and archived_tasks

Revision ID: d985baeab5c6
Revises: 308aed7c3449
Create Date: 2026-04-05 23:21:14.363984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd985baeab5c6'
down_revision: Union[str, Sequence[str], None] = '308aed7c3449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skip_verification', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skip_verification', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('skip_verification')

    with op.batch_alter_table('archived_tasks', schema=None) as batch_op:
        batch_op.drop_column('skip_verification')

    # ### end Alembic commands ###
