"""add paused_at column to playbook_runs

Revision ID: e43d09839087
Revises: 7a4c8681d23f
Create Date: 2026-04-09 14:25:08.715959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e43d09839087'
down_revision: Union[str, Sequence[str], None] = '7a4c8681d23f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playbook_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paused_at', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playbook_runs', schema=None) as batch_op:
        batch_op.drop_column('paused_at')

    # ### end Alembic commands ###
