"""add project_constraints table

Revision ID: f322b4dc379d
Revises: f6f7c1049974
Create Date: 2026-04-09 19:25:36.260865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f322b4dc379d'
down_revision: Union[str, Sequence[str], None] = 'f6f7c1049974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_constraints',
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('exclusive', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_agents_by_type', sa.Text(), server_default='{}', nullable=False),
    sa.Column('pause_scheduling', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_constraints')
    # ### end Alembic commands ###
