"""add workflow_id nullable FK to tasks and archived_tasks

Revision ID: f6f7c1049974
Revises: 6402d0c331c4
Create Date: 2026-04-09 18:15:26.008473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6f7c1049974'
down_revision: Union[str, Sequence[str], None] = '6402d0c331c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workflow_id', sa.Text(), nullable=True))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workflow_id', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_tasks_workflow_id', 'workflows', ['workflow_id'], ['workflow_id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_workflow_id', type_='foreignkey')
        batch_op.drop_column('workflow_id')

    with op.batch_alter_table('archived_tasks', schema=None) as batch_op:
        batch_op.drop_column('workflow_id')

    # ### end Alembic commands ###
