"""Database backend protocol (trait) defining all required operations.

Any database adapter must implement this protocol. The protocol is
organized by domain: projects, profiles, repos, tasks, dependencies,
agents, workspaces, tokens, results, events, hooks, hook runs, archives,
and chat analyzer suggestions.

Usage::

    def needs_db(db: DatabaseBackend) -> None:
        ...  # type-checker ensures db has all required methods

To add a new backend (e.g. PostgreSQL), implement a class satisfying
every method in this protocol.
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from src.models import (
    Agent,
    AgentProfile,
    AgentState,
    Hook,
    HookRun,
    Project,
    ProjectStatus,
    RepoConfig,
    Task,
    TaskStatus,
    Workspace,
)


@runtime_checkable
class DatabaseBackend(Protocol):
    """Trait defining the full database access contract.

    Every public method that the rest of the codebase calls on ``Database``
    must appear here.  Adapters (SQLite, PostgreSQL, …) implement this
    protocol so consumers are backend-agnostic.
    """

    # --- Lifecycle ---

    async def initialize(self) -> None:
        """Create tables, run migrations, and prepare the connection."""
        ...

    async def close(self) -> None:
        """Gracefully shut down the database connection."""
        ...

    # --- Projects ---

    async def create_project(self, project: Project) -> None: ...
    async def get_project(self, project_id: str) -> Project | None: ...
    async def list_projects(self, status: ProjectStatus | None = None) -> list[Project]: ...
    async def update_project(self, project_id: str, **kwargs) -> None: ...
    async def delete_project(self, project_id: str) -> None: ...

    # --- Agent Profiles ---

    async def create_profile(self, profile: AgentProfile) -> None: ...
    async def get_profile(self, profile_id: str) -> AgentProfile | None: ...
    async def list_profiles(self) -> list[AgentProfile]: ...
    async def update_profile(self, profile_id: str, **kwargs) -> None: ...
    async def delete_profile(self, profile_id: str) -> None: ...

    # --- Repos ---

    async def create_repo(self, repo: RepoConfig) -> None: ...
    async def get_repo(self, repo_id: str) -> RepoConfig | None: ...
    async def list_repos(self, project_id: str | None = None) -> list[RepoConfig]: ...
    async def update_repo(self, repo_id: str, **kwargs) -> None: ...
    async def delete_repo(self, repo_id: str) -> None: ...

    # --- Tasks ---

    async def create_task(self, task: Task) -> None: ...
    async def get_task(self, task_id: str) -> Task | None: ...
    async def list_tasks(
        self,
        project_id: str | None = None,
        status: TaskStatus | None = None,
    ) -> list[Task]: ...
    async def list_active_tasks(
        self,
        project_id: str | None = None,
        exclude_statuses: set[TaskStatus] | None = None,
    ) -> list[Task]: ...
    async def list_active_tasks_all_projects(self) -> list[Task]: ...
    async def count_tasks_by_status(
        self,
        project_id: str | None = None,
    ) -> dict[str, int]: ...
    async def update_task(self, task_id: str, **kwargs) -> None: ...
    async def transition_task(
        self,
        task_id: str,
        new_status: TaskStatus,
        *,
        context: str = "",
        **kwargs,
    ) -> None: ...
    async def delete_task(self, task_id: str) -> None: ...
    async def get_task_updated_at(self, task_id: str) -> float | None: ...
    async def get_task_created_at(self, task_id: str) -> float | None: ...
    async def add_task_context(
        self,
        task_id: str,
        *,
        type: str,
        label: str,
        content: str,
    ) -> str: ...
    async def get_task_contexts(self, task_id: str) -> list[dict]: ...
    async def set_task_meta(self, task_id: str, key: str, value) -> None: ...
    async def get_task_meta(self, task_id: str, key: str): ...
    async def get_all_task_meta(self, task_id: str) -> dict: ...
    async def delete_task_meta(self, task_id: str, key: str) -> None: ...
    async def get_subtasks(self, parent_task_id: str) -> list[Task]: ...
    async def get_task_tree(self, root_task_id: str) -> dict | None: ...
    async def get_parent_tasks(self, project_id: str) -> list[Task]: ...

    # --- Dependencies ---

    async def add_dependency(self, task_id: str, depends_on: str) -> None: ...
    async def get_dependencies(self, task_id: str) -> set[str]: ...
    async def get_all_dependencies(self) -> dict[str, set[str]]: ...
    async def are_dependencies_met(self, task_id: str) -> bool: ...
    async def get_stuck_defined_tasks(self, threshold_seconds: int) -> list[Task]: ...
    async def get_blocking_dependencies(
        self,
        task_id: str,
    ) -> list[tuple[str, str, str]]: ...
    async def get_dependents(self, task_id: str) -> set[str]: ...
    async def get_dependency_map_for_tasks(
        self,
        task_ids: list[str],
    ) -> dict[str, dict]: ...
    async def remove_dependency(self, task_id: str, depends_on: str) -> None: ...
    async def remove_all_dependencies_on(self, depends_on_task_id: str) -> None: ...

    # --- Agents ---

    async def create_agent(self, agent: Agent) -> None: ...
    async def get_agent(self, agent_id: str) -> Agent | None: ...
    async def list_agents(self, state: AgentState | None = None) -> list[Agent]: ...
    async def update_agent(self, agent_id: str, **kwargs) -> None: ...
    async def delete_agent(self, agent_id: str) -> None: ...

    # --- Workspaces ---

    async def create_workspace(self, workspace: Workspace) -> None: ...
    async def get_workspace(self, workspace_id: str) -> Workspace | None: ...
    async def get_workspace_by_name(
        self,
        project_id: str,
        name: str,
    ) -> Workspace | None: ...
    async def list_workspaces(
        self,
        project_id: str | None = None,
    ) -> list[Workspace]: ...
    async def delete_workspace(self, workspace_id: str) -> None: ...
    async def acquire_workspace(
        self,
        project_id: str,
        agent_id: str,
        task_id: str,
        preferred_workspace_id: str | None = None,
    ) -> Workspace | None: ...
    async def release_workspace(self, workspace_id: str) -> None: ...
    async def release_workspaces_for_agent(self, agent_id: str) -> int: ...
    async def release_workspaces_for_task(self, task_id: str) -> int: ...
    async def get_workspace_for_task(self, task_id: str) -> Workspace | None: ...
    async def get_project_workspace_path(self, project_id: str) -> str | None: ...
    async def count_available_workspaces(self, project_id: str) -> int: ...

    # --- Token Ledger ---

    async def record_token_usage(
        self,
        project_id: str,
        agent_id: str,
        task_id: str,
        tokens: int,
    ) -> None: ...
    async def get_project_token_usage(
        self,
        project_id: str,
        since: float | None = None,
    ) -> int: ...
    async def get_token_audit(
        self,
        days: int = 7,
        project_id: str | None = None,
    ) -> dict: ...

    # --- Task Results ---

    async def save_task_result(
        self,
        task_id: str,
        agent_id: str,
        output,
    ) -> None: ...
    async def get_task_result(self, task_id: str) -> dict | None: ...
    async def get_task_results(self, task_id: str) -> list[dict]: ...

    # --- Events ---

    async def log_event(
        self,
        event_type: str,
        project_id: str | None = None,
        task_id: str | None = None,
        agent_id: str | None = None,
        payload: str | None = None,
    ) -> None: ...
    async def get_recent_events(self, limit: int = 50) -> list[dict]: ...

    # --- Hooks ---

    async def create_hook(self, hook: Hook) -> None: ...
    async def get_hook(self, hook_id: str) -> Hook | None: ...
    async def list_hooks(
        self,
        project_id: str | None = None,
        enabled: bool | None = None,
    ) -> list[Hook]: ...
    async def update_hook(self, hook_id: str, **kwargs) -> None: ...
    async def delete_hook(self, hook_id: str) -> None: ...
    async def list_hooks_by_id_prefix(self, prefix: str) -> list[Hook]: ...
    async def delete_hooks_by_id_prefix(self, prefix: str) -> int: ...

    # --- Hook Runs ---

    async def create_hook_run(self, run: HookRun) -> None: ...
    async def update_hook_run(self, run_id: str, **kwargs) -> None: ...
    async def get_last_hook_run(self, hook_id: str) -> HookRun | None: ...
    async def list_hook_runs(
        self,
        hook_id: str,
        limit: int = 20,
    ) -> list[HookRun]: ...
    async def list_hook_runs_by_prefix(
        self,
        hook_id_prefix: str,
        limit: int = 20,
    ) -> list[HookRun]: ...

    # --- Atomic Operations ---

    async def assign_task_to_agent(self, task_id: str, agent_id: str) -> None: ...

    # --- Archived Tasks ---

    async def archive_task(self, task_id: str) -> bool: ...
    async def archive_completed_tasks(
        self,
        project_id: str | None = None,
    ) -> list[str]: ...
    async def archive_old_terminal_tasks(
        self,
        statuses: list[str],
        older_than_seconds: float,
    ) -> list[str]: ...
    async def list_archived_tasks(
        self,
        project_id: str | None = None,
        limit: int = 50,
    ) -> list[dict]: ...
    async def get_archived_task(self, task_id: str) -> dict | None: ...
    async def restore_archived_task(self, task_id: str) -> bool: ...
    async def delete_archived_task(self, task_id: str) -> bool: ...
    async def count_archived_tasks(
        self,
        project_id: str | None = None,
    ) -> int: ...

    # --- Chat Analyzer Suggestions ---

    async def create_chat_analyzer_suggestion(
        self,
        project_id: str,
        channel_id: int,
        suggestion_type: str,
        suggestion_text: str,
        suggestion_hash: str,
        context_snapshot: str | None = None,
    ) -> int: ...
    async def resolve_chat_analyzer_suggestion(
        self,
        suggestion_id: int,
        status: str,
    ) -> None: ...
    async def get_suggestion_hash_exists(
        self,
        project_id: str,
        suggestion_hash: str,
    ) -> bool: ...
    async def count_recent_suggestions(
        self,
        project_id: str,
        since: float,
    ) -> int: ...
    async def get_suggestion(self, suggestion_id: int) -> dict | None: ...
    async def get_recent_suggestions(
        self,
        channel_id: int,
        hours: int = 24,
    ) -> list[dict]: ...
    async def update_suggestion_status(
        self,
        suggestion_id: int,
        status: str,
        resolved_at: float | None = None,
    ) -> None: ...
    async def get_last_dismiss_time(
        self,
        project_id: str,
        channel_id: int,
    ) -> float | None: ...
    async def get_analyzer_suggestion_stats(
        self,
        project_id: str | None = None,
    ) -> dict: ...
    async def get_analyzer_suggestion_history(
        self,
        project_id: str | None = None,
        limit: int = 20,
    ) -> list[dict]: ...
